<!--<footer class="footer bg-color4 border-top-color3">
    <div class="container">
        <p>Place sticky footer content here.</p>
    </div>
</footer>-->


<script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
<script>
//$(document).ready(function(){
//    $('[data-toggle="tooltip"]').tooltip();
//});
</script>
</body>
</html>
