/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;


import com.github.gtmelo.sistci_api.data.Keys;
import com.github.gtmelo.sistci_api.data.Sistci;
import com.github.gtmelo.sistci_api.data.tables.records.AutoridadeRatificadoraRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutoridadeRatificadora extends TableImpl<AutoridadeRatificadoraRecord> {

    private static final long serialVersionUID = 70540985;

    /**
     * The reference instance of <code>sistci.autoridade_ratificadora</code>
     */
    public static final AutoridadeRatificadora AUTORIDADE_RATIFICADORA = new AutoridadeRatificadora();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AutoridadeRatificadoraRecord> getRecordType() {
        return AutoridadeRatificadoraRecord.class;
    }

    /**
     * The column <code>sistci.autoridade_ratificadora.id</code>.
     */
    public final TableField<AutoridadeRatificadoraRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.autoridade_ratificadora.nome</code>.
     */
    public final TableField<AutoridadeRatificadoraRecord, String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(254), this, "");

    /**
     * The column <code>sistci.autoridade_ratificadora.cargo</code>.
     */
    public final TableField<AutoridadeRatificadoraRecord, String> CARGO = createField("cargo", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

    /**
     * Create a <code>sistci.autoridade_ratificadora</code> table reference
     */
    public AutoridadeRatificadora() {
        this("autoridade_ratificadora", null);
    }

    /**
     * Create an aliased <code>sistci.autoridade_ratificadora</code> table reference
     */
    public AutoridadeRatificadora(String alias) {
        this(alias, AUTORIDADE_RATIFICADORA);
    }

    private AutoridadeRatificadora(String alias, Table<AutoridadeRatificadoraRecord> aliased) {
        this(alias, aliased, null);
    }

    private AutoridadeRatificadora(String alias, Table<AutoridadeRatificadoraRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sistci.SISTCI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AutoridadeRatificadoraRecord, Integer> getIdentity() {
        return Keys.IDENTITY_AUTORIDADE_RATIFICADORA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AutoridadeRatificadoraRecord> getPrimaryKey() {
        return Keys.KEY_AUTORIDADE_RATIFICADORA_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AutoridadeRatificadoraRecord>> getKeys() {
        return Arrays.<UniqueKey<AutoridadeRatificadoraRecord>>asList(Keys.KEY_AUTORIDADE_RATIFICADORA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutoridadeRatificadora as(String alias) {
        return new AutoridadeRatificadora(alias, this);
    }

    /**
     * Rename this table
     */
    public AutoridadeRatificadora rename(String name) {
        return new AutoridadeRatificadora(name, null);
    }
}
