/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutoridadeRatificadora extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.AutoridadeRatificadoraRecord> {

	private static final long serialVersionUID = 100124650;

	/**
	 * The singleton instance of <code>sistci.autoridade_ratificadora</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.AutoridadeRatificadora AUTORIDADE_RATIFICADORA = new com.github.gtmelo.sistci_api.data.tables.AutoridadeRatificadora();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.AutoridadeRatificadoraRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.AutoridadeRatificadoraRecord.class;
	}

	/**
	 * The column <code>sistci.autoridade_ratificadora.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.AutoridadeRatificadoraRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.autoridade_ratificadora.nome</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.AutoridadeRatificadoraRecord, java.lang.String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(254), this, "");

	/**
	 * The column <code>sistci.autoridade_ratificadora.cargo</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.AutoridadeRatificadoraRecord, java.lang.String> CARGO = createField("cargo", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * Create a <code>sistci.autoridade_ratificadora</code> table reference
	 */
	public AutoridadeRatificadora() {
		this("autoridade_ratificadora", null);
	}

	/**
	 * Create an aliased <code>sistci.autoridade_ratificadora</code> table reference
	 */
	public AutoridadeRatificadora(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.AutoridadeRatificadora.AUTORIDADE_RATIFICADORA);
	}

	private AutoridadeRatificadora(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.AutoridadeRatificadoraRecord> aliased) {
		this(alias, aliased, null);
	}

	private AutoridadeRatificadora(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.AutoridadeRatificadoraRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.AutoridadeRatificadoraRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_AUTORIDADE_RATIFICADORA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.AutoridadeRatificadoraRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_AUTORIDADE_RATIFICADORA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.AutoridadeRatificadoraRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.AutoridadeRatificadoraRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_AUTORIDADE_RATIFICADORA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.AutoridadeRatificadora as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.AutoridadeRatificadora(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.AutoridadeRatificadora rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.AutoridadeRatificadora(name, null);
	}
}
