/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;


import com.github.gtmelo.sistci_api.data.Keys;
import com.github.gtmelo.sistci_api.data.Sistci;
import com.github.gtmelo.sistci_api.data.tables.records.CargoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cargo extends TableImpl<CargoRecord> {

    private static final long serialVersionUID = 604169806;

    /**
     * The reference instance of <code>sistci.cargo</code>
     */
    public static final Cargo CARGO = new Cargo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CargoRecord> getRecordType() {
        return CargoRecord.class;
    }

    /**
     * The column <code>sistci.cargo.id</code>.
     */
    public final TableField<CargoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.cargo.descricao</code>.
     */
    public final TableField<CargoRecord, String> DESCRICAO = createField("descricao", org.jooq.impl.SQLDataType.VARCHAR.length(254), this, "");

    /**
     * The column <code>sistci.cargo.orgaoid</code>.
     */
    public final TableField<CargoRecord, Integer> ORGAOID = createField("orgaoid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * Create a <code>sistci.cargo</code> table reference
     */
    public Cargo() {
        this("cargo", null);
    }

    /**
     * Create an aliased <code>sistci.cargo</code> table reference
     */
    public Cargo(String alias) {
        this(alias, CARGO);
    }

    private Cargo(String alias, Table<CargoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cargo(String alias, Table<CargoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sistci.SISTCI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CargoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CARGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CargoRecord> getPrimaryKey() {
        return Keys.KEY_CARGO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CargoRecord>> getKeys() {
        return Arrays.<UniqueKey<CargoRecord>>asList(Keys.KEY_CARGO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CargoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CargoRecord, ?>>asList(Keys.CARGO_ORGAO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cargo as(String alias) {
        return new Cargo(alias, this);
    }

    /**
     * Rename this table
     */
    public Cargo rename(String name) {
        return new Cargo(name, null);
    }
}
