/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;


import com.github.gtmelo.sistci_api.data.Keys;
import com.github.gtmelo.sistci_api.data.Sistci;
import com.github.gtmelo.sistci_api.data.tables.records.CidicRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cidic extends TableImpl<CidicRecord> {

    private static final long serialVersionUID = 306778488;

    /**
     * The reference instance of <code>sistci.cidic</code>
     */
    public static final Cidic CIDIC = new Cidic();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CidicRecord> getRecordType() {
        return CidicRecord.class;
    }

    /**
     * The column <code>sistci.cidic.id</code>.
     */
    public final TableField<CidicRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.cidic.cidic</code>.
     */
    public final TableField<CidicRecord, String> CIDIC_ = createField("cidic", org.jooq.impl.SQLDataType.VARCHAR.length(254), this, "");

    /**
     * Create a <code>sistci.cidic</code> table reference
     */
    public Cidic() {
        this("cidic", null);
    }

    /**
     * Create an aliased <code>sistci.cidic</code> table reference
     */
    public Cidic(String alias) {
        this(alias, CIDIC);
    }

    private Cidic(String alias, Table<CidicRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cidic(String alias, Table<CidicRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sistci.SISTCI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CidicRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CIDIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CidicRecord> getPrimaryKey() {
        return Keys.KEY_CIDIC_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CidicRecord>> getKeys() {
        return Arrays.<UniqueKey<CidicRecord>>asList(Keys.KEY_CIDIC_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cidic as(String alias) {
        return new Cidic(alias, this);
    }

    /**
     * Rename this table
     */
    public Cidic rename(String name) {
        return new Cidic(name, null);
    }
}
