/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;


import com.github.gtmelo.sistci_api.data.Keys;
import com.github.gtmelo.sistci_api.data.Sistci;
import com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Classificacao extends TableImpl<ClassificacaoRecord> {

    private static final long serialVersionUID = 1983287269;

    /**
     * The reference instance of <code>sistci.classificacao</code>
     */
    public static final Classificacao CLASSIFICACAO = new Classificacao();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ClassificacaoRecord> getRecordType() {
        return ClassificacaoRecord.class;
    }

    /**
     * The column <code>sistci.classificacao.id</code>.
     */
    public final TableField<ClassificacaoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.classificacao.autoridade_ratificadoraid</code>.
     */
    public final TableField<ClassificacaoRecord, Integer> AUTORIDADE_RATIFICADORAID = createField("autoridade_ratificadoraid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>sistci.classificacao.operacaoid</code>.
     */
    public final TableField<ClassificacaoRecord, Integer> OPERACAOID = createField("operacaoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>sistci.classificacao</code> table reference
     */
    public Classificacao() {
        this("classificacao", null);
    }

    /**
     * Create an aliased <code>sistci.classificacao</code> table reference
     */
    public Classificacao(String alias) {
        this(alias, CLASSIFICACAO);
    }

    private Classificacao(String alias, Table<ClassificacaoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Classificacao(String alias, Table<ClassificacaoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sistci.SISTCI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ClassificacaoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CLASSIFICACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ClassificacaoRecord> getPrimaryKey() {
        return Keys.KEY_CLASSIFICACAO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ClassificacaoRecord>> getKeys() {
        return Arrays.<UniqueKey<ClassificacaoRecord>>asList(Keys.KEY_CLASSIFICACAO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ClassificacaoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ClassificacaoRecord, ?>>asList(Keys.CLASSIFICACAO_AUTORIDADE_RATIFICADORA, Keys.FKCLASSIFICA26679);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Classificacao as(String alias) {
        return new Classificacao(alias, this);
    }

    /**
     * Rename this table
     */
    public Classificacao rename(String name) {
        return new Classificacao(name, null);
    }
}
