/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Classificacao extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord> {

	private static final long serialVersionUID = -1595096136;

	/**
	 * The singleton instance of <code>sistci.classificacao</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Classificacao CLASSIFICACAO = new com.github.gtmelo.sistci_api.data.tables.Classificacao();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord.class;
	}

	/**
	 * The column <code>sistci.classificacao.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.classificacao.autoridade_ratificadoraid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord, java.lang.Integer> AUTORIDADE_RATIFICADORAID = createField("autoridade_ratificadoraid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>sistci.classificacao.operacaoid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord, java.lang.Integer> OPERACAOID = createField("operacaoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>sistci.classificacao</code> table reference
	 */
	public Classificacao() {
		this("classificacao", null);
	}

	/**
	 * Create an aliased <code>sistci.classificacao</code> table reference
	 */
	public Classificacao(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.Classificacao.CLASSIFICACAO);
	}

	private Classificacao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Classificacao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_CLASSIFICACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_CLASSIFICACAO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_CLASSIFICACAO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord, ?>>asList(com.github.gtmelo.sistci_api.data.Keys.CLASSIFICACAO_AUTORIDADE_RATIFICADORA, com.github.gtmelo.sistci_api.data.Keys.FKCLASSIFICA26679);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.Classificacao as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.Classificacao(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.Classificacao rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.Classificacao(name, null);
	}
}
