/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CpadsPessoa extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.CpadsPessoaRecord> {

	private static final long serialVersionUID = 542483806;

	/**
	 * The singleton instance of <code>sistci.cpads_pessoa</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.CpadsPessoa CPADS_PESSOA = new com.github.gtmelo.sistci_api.data.tables.CpadsPessoa();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.CpadsPessoaRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.CpadsPessoaRecord.class;
	}

	/**
	 * The column <code>sistci.cpads_pessoa.cpadsid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.CpadsPessoaRecord, java.lang.Integer> CPADSID = createField("cpadsid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.cpads_pessoa.pessoaid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.CpadsPessoaRecord, java.lang.Integer> PESSOAID = createField("pessoaid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>sistci.cpads_pessoa</code> table reference
	 */
	public CpadsPessoa() {
		this("cpads_pessoa", null);
	}

	/**
	 * Create an aliased <code>sistci.cpads_pessoa</code> table reference
	 */
	public CpadsPessoa(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.CpadsPessoa.CPADS_PESSOA);
	}

	private CpadsPessoa(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.CpadsPessoaRecord> aliased) {
		this(alias, aliased, null);
	}

	private CpadsPessoa(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.CpadsPessoaRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.CpadsPessoaRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_CPADS_PESSOA_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.CpadsPessoaRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.CpadsPessoaRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_CPADS_PESSOA_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.CpadsPessoaRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.CpadsPessoaRecord, ?>>asList(com.github.gtmelo.sistci_api.data.Keys.CPADS_PESSOA, com.github.gtmelo.sistci_api.data.Keys.FKCPADS_PESS956983);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.CpadsPessoa as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.CpadsPessoa(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.CpadsPessoa rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.CpadsPessoa(name, null);
	}
}
