/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;


import com.github.gtmelo.sistci_api.data.Keys;
import com.github.gtmelo.sistci_api.data.Sistci;
import com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cpads extends TableImpl<CpadsRecord> {

    private static final long serialVersionUID = -2021505180;

    /**
     * The reference instance of <code>sistci.cpads</code>
     */
    public static final Cpads CPADS = new Cpads();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CpadsRecord> getRecordType() {
        return CpadsRecord.class;
    }

    /**
     * The column <code>sistci.cpads.id</code>.
     */
    public final TableField<CpadsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.cpads.orgaoid</code>.
     */
    public final TableField<CpadsRecord, Integer> ORGAOID = createField("orgaoid", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>sistci.cpads.portaria_nomeacao</code>.
     */
    public final TableField<CpadsRecord, String> PORTARIA_NOMEACAO = createField("portaria_nomeacao", org.jooq.impl.SQLDataType.VARCHAR.length(254), this, "");

    /**
     * The column <code>sistci.cpads.data_formacao</code>.
     */
    public final TableField<CpadsRecord, Date> DATA_FORMACAO = createField("data_formacao", org.jooq.impl.SQLDataType.DATE, this, "");

    /**
     * Create a <code>sistci.cpads</code> table reference
     */
    public Cpads() {
        this("cpads", null);
    }

    /**
     * Create an aliased <code>sistci.cpads</code> table reference
     */
    public Cpads(String alias) {
        this(alias, CPADS);
    }

    private Cpads(String alias, Table<CpadsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Cpads(String alias, Table<CpadsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sistci.SISTCI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CpadsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CPADS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CpadsRecord> getPrimaryKey() {
        return Keys.KEY_CPADS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CpadsRecord>> getKeys() {
        return Arrays.<UniqueKey<CpadsRecord>>asList(Keys.KEY_CPADS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<CpadsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CpadsRecord, ?>>asList(Keys.ORGAO_CPADS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Cpads as(String alias) {
        return new Cpads(alias, this);
    }

    /**
     * Rename this table
     */
    public Cpads rename(String name) {
        return new Cpads(name, null);
    }
}
