/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Cpads extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord> {

	private static final long serialVersionUID = -1575991509;

	/**
	 * The singleton instance of <code>sistci.cpads</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Cpads CPADS = new com.github.gtmelo.sistci_api.data.tables.Cpads();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord.class;
	}

	/**
	 * The column <code>sistci.cpads.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.cpads.portaria_nomeacao</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord, java.lang.String> PORTARIA_NOMEACAO = createField("portaria_nomeacao", org.jooq.impl.SQLDataType.VARCHAR.length(254), this, "");

	/**
	 * The column <code>sistci.cpads.data_formacao</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord, java.sql.Date> DATA_FORMACAO = createField("data_formacao", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>sistci.cpads.orgaoid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord, java.lang.Integer> ORGAOID = createField("orgaoid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>sistci.cpads</code> table reference
	 */
	public Cpads() {
		this("cpads", null);
	}

	/**
	 * Create an aliased <code>sistci.cpads</code> table reference
	 */
	public Cpads(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.Cpads.CPADS);
	}

	private Cpads(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Cpads(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_CPADS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_CPADS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_CPADS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord, ?>>asList(com.github.gtmelo.sistci_api.data.Keys.ORGAO_CPADS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.Cpads as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.Cpads(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.Cpads rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.Cpads(name, null);
	}
}
