/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Desclassificacao extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord> {

	private static final long serialVersionUID = 1905686656;

	/**
	 * The singleton instance of <code>sistci.desclassificacao</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Desclassificacao DESCLASSIFICACAO = new com.github.gtmelo.sistci_api.data.tables.Desclassificacao();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord.class;
	}

	/**
	 * The column <code>sistci.desclassificacao.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.desclassificacao.data</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord, java.sql.Date> DATA = createField("data", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>sistci.desclassificacao.imagem</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord, java.lang.String> IMAGEM = createField("imagem", org.jooq.impl.SQLDataType.VARCHAR.length(254), this, "");

	/**
	 * The column <code>sistci.desclassificacao.pessoaid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord, java.lang.Integer> PESSOAID = createField("pessoaid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>sistci.desclassificacao.autoridadeid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord, java.lang.Integer> AUTORIDADEID = createField("autoridadeid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.desclassificacao.tciid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord, java.lang.Integer> TCIID = createField("tciid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>sistci.desclassificacao</code> table reference
	 */
	public Desclassificacao() {
		this("desclassificacao", null);
	}

	/**
	 * Create an aliased <code>sistci.desclassificacao</code> table reference
	 */
	public Desclassificacao(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.Desclassificacao.DESCLASSIFICACAO);
	}

	private Desclassificacao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Desclassificacao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_DESCLASSIFICACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_DESCLASSIFICACAO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_DESCLASSIFICACAO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord, ?>>asList(com.github.gtmelo.sistci_api.data.Keys.PESSOA_DESCLASSIFICACAO, com.github.gtmelo.sistci_api.data.Keys.AUTORIDADE_DESCLASSIFICACAO, com.github.gtmelo.sistci_api.data.Keys.TCI_DESCLASSIFICACAO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.Desclassificacao as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.Desclassificacao(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.Desclassificacao rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.Desclassificacao(name, null);
	}
}
