/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;


import com.github.gtmelo.sistci_api.data.Keys;
import com.github.gtmelo.sistci_api.data.Sistci;
import com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Desclassificacao extends TableImpl<DesclassificacaoRecord> {

    private static final long serialVersionUID = 1151491839;

    /**
     * The reference instance of <code>sistci.desclassificacao</code>
     */
    public static final Desclassificacao DESCLASSIFICACAO = new Desclassificacao();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DesclassificacaoRecord> getRecordType() {
        return DesclassificacaoRecord.class;
    }

    /**
     * The column <code>sistci.desclassificacao.id</code>.
     */
    public final TableField<DesclassificacaoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.desclassificacao.operacaoid</code>.
     */
    public final TableField<DesclassificacaoRecord, Integer> OPERACAOID = createField("operacaoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>sistci.desclassificacao</code> table reference
     */
    public Desclassificacao() {
        this("desclassificacao", null);
    }

    /**
     * Create an aliased <code>sistci.desclassificacao</code> table reference
     */
    public Desclassificacao(String alias) {
        this(alias, DESCLASSIFICACAO);
    }

    private Desclassificacao(String alias, Table<DesclassificacaoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Desclassificacao(String alias, Table<DesclassificacaoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sistci.SISTCI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DesclassificacaoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DESCLASSIFICACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DesclassificacaoRecord> getPrimaryKey() {
        return Keys.KEY_DESCLASSIFICACAO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DesclassificacaoRecord>> getKeys() {
        return Arrays.<UniqueKey<DesclassificacaoRecord>>asList(Keys.KEY_DESCLASSIFICACAO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<DesclassificacaoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DesclassificacaoRecord, ?>>asList(Keys.FKDESCLASSIF626384);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Desclassificacao as(String alias) {
        return new Desclassificacao(alias, this);
    }

    /**
     * Rename this table
     */
    public Desclassificacao rename(String name) {
        return new Desclassificacao(name, null);
    }
}
