/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FundamentoLegal extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.FundamentoLegalRecord> {

	private static final long serialVersionUID = 421213333;

	/**
	 * The singleton instance of <code>sistci.fundamento_legal</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.FundamentoLegal FUNDAMENTO_LEGAL = new com.github.gtmelo.sistci_api.data.tables.FundamentoLegal();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.FundamentoLegalRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.FundamentoLegalRecord.class;
	}

	/**
	 * The column <code>sistci.fundamento_legal.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.FundamentoLegalRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.fundamento_legal.descricao</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.FundamentoLegalRecord, java.lang.String> DESCRICAO = createField("descricao", org.jooq.impl.SQLDataType.VARCHAR.length(254).nullable(false), this, "");

	/**
	 * Create a <code>sistci.fundamento_legal</code> table reference
	 */
	public FundamentoLegal() {
		this("fundamento_legal", null);
	}

	/**
	 * Create an aliased <code>sistci.fundamento_legal</code> table reference
	 */
	public FundamentoLegal(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.FundamentoLegal.FUNDAMENTO_LEGAL);
	}

	private FundamentoLegal(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.FundamentoLegalRecord> aliased) {
		this(alias, aliased, null);
	}

	private FundamentoLegal(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.FundamentoLegalRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.FundamentoLegalRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_FUNDAMENTO_LEGAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.FundamentoLegalRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_FUNDAMENTO_LEGAL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.FundamentoLegalRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.FundamentoLegalRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_FUNDAMENTO_LEGAL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.FundamentoLegal as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.FundamentoLegal(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.FundamentoLegal rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.FundamentoLegal(name, null);
	}
}
