/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrauSigilo extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord> {

	private static final long serialVersionUID = 228343686;

	/**
	 * The singleton instance of <code>sistci.grau_sigilo</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.GrauSigilo GRAU_SIGILO = new com.github.gtmelo.sistci_api.data.tables.GrauSigilo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord.class;
	}

	/**
	 * The column <code>sistci.grau_sigilo.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.grau_sigilo.abreviacao</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord, java.lang.String> ABREVIACAO = createField("abreviacao", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

	/**
	 * The column <code>sistci.grau_sigilo.descricao</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord, java.lang.String> DESCRICAO = createField("descricao", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * The column <code>sistci.grau_sigilo.permite_prorrogacao</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord, java.lang.Integer> PERMITE_PRORROGACAO = createField("permite_prorrogacao", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>sistci.grau_sigilo</code> table reference
	 */
	public GrauSigilo() {
		this("grau_sigilo", null);
	}

	/**
	 * Create an aliased <code>sistci.grau_sigilo</code> table reference
	 */
	public GrauSigilo(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.GrauSigilo.GRAU_SIGILO);
	}

	private GrauSigilo(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord> aliased) {
		this(alias, aliased, null);
	}

	private GrauSigilo(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_GRAU_SIGILO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_GRAU_SIGILO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_GRAU_SIGILO_PRIMARY, com.github.gtmelo.sistci_api.data.Keys.KEY_GRAU_SIGILO_ABREVIACAO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.GrauSigilo as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.GrauSigilo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.GrauSigilo rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.GrauSigilo(name, null);
	}
}
