/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;


import com.github.gtmelo.sistci_api.data.Keys;
import com.github.gtmelo.sistci_api.data.Sistci;
import com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrauSigilo extends TableImpl<GrauSigiloRecord> {

    private static final long serialVersionUID = 767162513;

    /**
     * The reference instance of <code>sistci.grau_sigilo</code>
     */
    public static final GrauSigilo GRAU_SIGILO = new GrauSigilo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GrauSigiloRecord> getRecordType() {
        return GrauSigiloRecord.class;
    }

    /**
     * The column <code>sistci.grau_sigilo.id</code>.
     */
    public final TableField<GrauSigiloRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.grau_sigilo.abreviacao</code>.
     */
    public final TableField<GrauSigiloRecord, String> ABREVIACAO = createField("abreviacao", org.jooq.impl.SQLDataType.VARCHAR.length(1).nullable(false), this, "");

    /**
     * The column <code>sistci.grau_sigilo.descricao</code>.
     */
    public final TableField<GrauSigiloRecord, String> DESCRICAO = createField("descricao", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

    /**
     * The column <code>sistci.grau_sigilo.permite_prorrogacao</code>.
     */
    public final TableField<GrauSigiloRecord, Integer> PERMITE_PRORROGACAO = createField("permite_prorrogacao", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>sistci.grau_sigilo</code> table reference
     */
    public GrauSigilo() {
        this("grau_sigilo", null);
    }

    /**
     * Create an aliased <code>sistci.grau_sigilo</code> table reference
     */
    public GrauSigilo(String alias) {
        this(alias, GRAU_SIGILO);
    }

    private GrauSigilo(String alias, Table<GrauSigiloRecord> aliased) {
        this(alias, aliased, null);
    }

    private GrauSigilo(String alias, Table<GrauSigiloRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sistci.SISTCI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<GrauSigiloRecord, Integer> getIdentity() {
        return Keys.IDENTITY_GRAU_SIGILO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GrauSigiloRecord> getPrimaryKey() {
        return Keys.KEY_GRAU_SIGILO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GrauSigiloRecord>> getKeys() {
        return Arrays.<UniqueKey<GrauSigiloRecord>>asList(Keys.KEY_GRAU_SIGILO_PRIMARY, Keys.KEY_GRAU_SIGILO_ABREVIACAO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GrauSigilo as(String alias) {
        return new GrauSigilo(alias, this);
    }

    /**
     * Rename this table
     */
    public GrauSigilo rename(String name) {
        return new GrauSigilo(name, null);
    }
}
