/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Operacao extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord> {

	private static final long serialVersionUID = -2004067612;

	/**
	 * The singleton instance of <code>sistci.operacao</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Operacao OPERACAO = new com.github.gtmelo.sistci_api.data.tables.Operacao();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord.class;
	}

	/**
	 * The column <code>sistci.operacao.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.operacao.statusid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord, java.lang.Integer> STATUSID = createField("statusid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.operacao.pessoaid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord, java.lang.Integer> PESSOAID = createField("pessoaid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.operacao.autoridadeid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord, java.lang.Integer> AUTORIDADEID = createField("autoridadeid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.operacao.tciid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord, java.lang.Integer> TCIID = createField("tciid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.operacao.data</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord, java.sql.Date> DATA = createField("data", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>sistci.operacao.imagem</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord, java.lang.String> IMAGEM = createField("imagem", org.jooq.impl.SQLDataType.VARCHAR.length(254).nullable(false), this, "");

	/**
	 * Create a <code>sistci.operacao</code> table reference
	 */
	public Operacao() {
		this("operacao", null);
	}

	/**
	 * Create an aliased <code>sistci.operacao</code> table reference
	 */
	public Operacao(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.Operacao.OPERACAO);
	}

	private Operacao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Operacao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_OPERACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_OPERACAO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_OPERACAO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord, ?>>asList(com.github.gtmelo.sistci_api.data.Keys.OPERACAO_STATUS, com.github.gtmelo.sistci_api.data.Keys.PESSOA_OPERACAO, com.github.gtmelo.sistci_api.data.Keys.AUTORIDADE_OPERACAO, com.github.gtmelo.sistci_api.data.Keys.TCI_OPERACAO);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.Operacao as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.Operacao(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.Operacao rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.Operacao(name, null);
	}
}
