/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;


import com.github.gtmelo.sistci_api.data.Keys;
import com.github.gtmelo.sistci_api.data.Sistci;
import com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organizacao extends TableImpl<OrganizacaoRecord> {

    private static final long serialVersionUID = 1463588334;

    /**
     * The reference instance of <code>sistci.organizacao</code>
     */
    public static final Organizacao ORGANIZACAO = new Organizacao();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrganizacaoRecord> getRecordType() {
        return OrganizacaoRecord.class;
    }

    /**
     * The column <code>sistci.organizacao.id</code>.
     */
    public final TableField<OrganizacaoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.organizacao.sigla</code>.
     */
    public final TableField<OrganizacaoRecord, String> SIGLA = createField("sigla", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

    /**
     * The column <code>sistci.organizacao.nome</code>.
     */
    public final TableField<OrganizacaoRecord, String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(254), this, "");

    /**
     * Create a <code>sistci.organizacao</code> table reference
     */
    public Organizacao() {
        this("organizacao", null);
    }

    /**
     * Create an aliased <code>sistci.organizacao</code> table reference
     */
    public Organizacao(String alias) {
        this(alias, ORGANIZACAO);
    }

    private Organizacao(String alias, Table<OrganizacaoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Organizacao(String alias, Table<OrganizacaoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sistci.SISTCI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<OrganizacaoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ORGANIZACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OrganizacaoRecord> getPrimaryKey() {
        return Keys.KEY_ORGANIZACAO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OrganizacaoRecord>> getKeys() {
        return Arrays.<UniqueKey<OrganizacaoRecord>>asList(Keys.KEY_ORGANIZACAO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Organizacao as(String alias) {
        return new Organizacao(alias, this);
    }

    /**
     * Rename this table
     */
    public Organizacao rename(String name) {
        return new Organizacao(name, null);
    }
}
