/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Orgao extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord> {

	private static final long serialVersionUID = 1768982301;

	/**
	 * The singleton instance of <code>sistci.orgao</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Orgao ORGAO = new com.github.gtmelo.sistci_api.data.tables.Orgao();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord.class;
	}

	/**
	 * The column <code>sistci.orgao.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.orgao.sigla</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord, java.lang.String> SIGLA = createField("sigla", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>sistci.orgao.nome</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord, java.lang.String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(254), this, "");

	/**
	 * The column <code>sistci.orgao.telefone</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord, java.lang.String> TELEFONE = createField("telefone", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>sistci.orgao.endereco</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord, java.lang.String> ENDERECO = createField("endereco", org.jooq.impl.SQLDataType.VARCHAR.length(254), this, "");

	/**
	 * The column <code>sistci.orgao.emailid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord, java.lang.Integer> EMAILID = createField("emailid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>sistci.orgao.orgao_superiorid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord, java.lang.Integer> ORGAO_SUPERIORID = createField("orgao_superiorid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>sistci.orgao</code> table reference
	 */
	public Orgao() {
		this("orgao", null);
	}

	/**
	 * Create an aliased <code>sistci.orgao</code> table reference
	 */
	public Orgao(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.Orgao.ORGAO);
	}

	private Orgao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Orgao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_ORGAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_ORGAO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_ORGAO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord, ?>>asList(com.github.gtmelo.sistci_api.data.Keys.ORGAO_EMAIL, com.github.gtmelo.sistci_api.data.Keys.ORGAO_SUPERIOR);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.Orgao as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.Orgao(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.Orgao rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.Orgao(name, null);
	}
}
