/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Organizacao extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord> {

	private static final long serialVersionUID = 1456914671;

	/**
	 * The singleton instance of <code>sistci.organizacao</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Organizacao ORGANIZACAO = new com.github.gtmelo.sistci_api.data.tables.Organizacao();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord.class;
	}

	/**
	 * The column <code>sistci.organizacao.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.organizacao.sigla</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord, java.lang.String> SIGLA = createField("sigla", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>sistci.organizacao.nome</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord, java.lang.String> NOME = createField("nome", org.jooq.impl.SQLDataType.VARCHAR.length(254), this, "");

	/**
	 * Create a <code>sistci.organizacao</code> table reference
	 */
	public Organizacao() {
		this("organizacao", null);
	}

	/**
	 * Create an aliased <code>sistci.organizacao</code> table reference
	 */
	public Organizacao(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.Organizacao.ORGANIZACAO);
	}

	private Organizacao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Organizacao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_ORGANIZACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_ORGANIZACAO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_ORGANIZACAO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.Organizacao as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.Organizacao(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.Organizacao rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.Organizacao(name, null);
	}
}
