/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;


import com.github.gtmelo.sistci_api.data.Keys;
import com.github.gtmelo.sistci_api.data.Sistci;
import com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Prazo extends TableImpl<PrazoRecord> {

    private static final long serialVersionUID = -176550926;

    /**
     * The reference instance of <code>sistci.prazo</code>
     */
    public static final Prazo PRAZO = new Prazo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PrazoRecord> getRecordType() {
        return PrazoRecord.class;
    }

    /**
     * The column <code>sistci.prazo.id</code>.
     */
    public final TableField<PrazoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.prazo.data</code>.
     */
    public final TableField<PrazoRecord, Date> DATA = createField("data", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>sistci.prazo.evento</code>.
     */
    public final TableField<PrazoRecord, String> EVENTO = createField("evento", org.jooq.impl.SQLDataType.VARCHAR.length(254), this, "");

    /**
     * Create a <code>sistci.prazo</code> table reference
     */
    public Prazo() {
        this("prazo", null);
    }

    /**
     * Create an aliased <code>sistci.prazo</code> table reference
     */
    public Prazo(String alias) {
        this(alias, PRAZO);
    }

    private Prazo(String alias, Table<PrazoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Prazo(String alias, Table<PrazoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sistci.SISTCI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PrazoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PRAZO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PrazoRecord> getPrimaryKey() {
        return Keys.KEY_PRAZO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PrazoRecord>> getKeys() {
        return Arrays.<UniqueKey<PrazoRecord>>asList(Keys.KEY_PRAZO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Prazo as(String alias) {
        return new Prazo(alias, this);
    }

    /**
     * Rename this table
     */
    public Prazo rename(String name) {
        return new Prazo(name, null);
    }
}
