/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Prazo extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord> {

	private static final long serialVersionUID = 1062368361;

	/**
	 * The singleton instance of <code>sistci.prazo</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Prazo PRAZO = new com.github.gtmelo.sistci_api.data.tables.Prazo();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord.class;
	}

	/**
	 * The column <code>sistci.prazo.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.prazo.data</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord, java.sql.Date> DATA = createField("data", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>sistci.prazo.evento</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord, java.lang.String> EVENTO = createField("evento", org.jooq.impl.SQLDataType.VARCHAR.length(254), this, "");

	/**
	 * Create a <code>sistci.prazo</code> table reference
	 */
	public Prazo() {
		this("prazo", null);
	}

	/**
	 * Create an aliased <code>sistci.prazo</code> table reference
	 */
	public Prazo(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.Prazo.PRAZO);
	}

	private Prazo(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Prazo(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_PRAZO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_PRAZO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_PRAZO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.Prazo as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.Prazo(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.Prazo rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.Prazo(name, null);
	}
}
