/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;


import com.github.gtmelo.sistci_api.data.Keys;
import com.github.gtmelo.sistci_api.data.Sistci;
import com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Prorrogacao extends TableImpl<ProrrogacaoRecord> {

    private static final long serialVersionUID = 281640177;

    /**
     * The reference instance of <code>sistci.prorrogacao</code>
     */
    public static final Prorrogacao PRORROGACAO = new Prorrogacao();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ProrrogacaoRecord> getRecordType() {
        return ProrrogacaoRecord.class;
    }

    /**
     * The column <code>sistci.prorrogacao.id</code>.
     */
    public final TableField<ProrrogacaoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.prorrogacao.prazoid</code>.
     */
    public final TableField<ProrrogacaoRecord, Integer> PRAZOID = createField("prazoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.prorrogacao.operacaoid</code>.
     */
    public final TableField<ProrrogacaoRecord, Integer> OPERACAOID = createField("operacaoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>sistci.prorrogacao</code> table reference
     */
    public Prorrogacao() {
        this("prorrogacao", null);
    }

    /**
     * Create an aliased <code>sistci.prorrogacao</code> table reference
     */
    public Prorrogacao(String alias) {
        this(alias, PRORROGACAO);
    }

    private Prorrogacao(String alias, Table<ProrrogacaoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Prorrogacao(String alias, Table<ProrrogacaoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sistci.SISTCI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ProrrogacaoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PRORROGACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ProrrogacaoRecord> getPrimaryKey() {
        return Keys.KEY_PRORROGACAO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ProrrogacaoRecord>> getKeys() {
        return Arrays.<UniqueKey<ProrrogacaoRecord>>asList(Keys.KEY_PRORROGACAO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ProrrogacaoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ProrrogacaoRecord, ?>>asList(Keys.PRORROGACAO_PRAZO, Keys.FKPRORROGACA31355);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Prorrogacao as(String alias) {
        return new Prorrogacao(alias, this);
    }

    /**
     * Rename this table
     */
    public Prorrogacao rename(String name) {
        return new Prorrogacao(name, null);
    }
}
