/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Prorrogacao extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord> {

	private static final long serialVersionUID = -1592022276;

	/**
	 * The singleton instance of <code>sistci.prorrogacao</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Prorrogacao PRORROGACAO = new com.github.gtmelo.sistci_api.data.tables.Prorrogacao();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord.class;
	}

	/**
	 * The column <code>sistci.prorrogacao.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.prorrogacao.prazoid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord, java.lang.Integer> PRAZOID = createField("prazoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.prorrogacao.operacaoid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord, java.lang.Integer> OPERACAOID = createField("operacaoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>sistci.prorrogacao</code> table reference
	 */
	public Prorrogacao() {
		this("prorrogacao", null);
	}

	/**
	 * Create an aliased <code>sistci.prorrogacao</code> table reference
	 */
	public Prorrogacao(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.Prorrogacao.PRORROGACAO);
	}

	private Prorrogacao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Prorrogacao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_PRORROGACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_PRORROGACAO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_PRORROGACAO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord, ?>>asList(com.github.gtmelo.sistci_api.data.Keys.PRORROGACAO_PRAZO, com.github.gtmelo.sistci_api.data.Keys.FKPRORROGACA31355);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.Prorrogacao as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.Prorrogacao(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.Prorrogacao rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.Prorrogacao(name, null);
	}
}
