/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;


import com.github.gtmelo.sistci_api.data.Keys;
import com.github.gtmelo.sistci_api.data.Sistci;
import com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reclassificacao extends TableImpl<ReclassificacaoRecord> {

    private static final long serialVersionUID = -112094803;

    /**
     * The reference instance of <code>sistci.reclassificacao</code>
     */
    public static final Reclassificacao RECLASSIFICACAO = new Reclassificacao();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReclassificacaoRecord> getRecordType() {
        return ReclassificacaoRecord.class;
    }

    /**
     * The column <code>sistci.reclassificacao.id</code>.
     */
    public final TableField<ReclassificacaoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.reclassificacao.grau_sigiloid</code>.
     */
    public final TableField<ReclassificacaoRecord, Integer> GRAU_SIGILOID = createField("grau_sigiloid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.reclassificacao.operacaoid</code>.
     */
    public final TableField<ReclassificacaoRecord, Integer> OPERACAOID = createField("operacaoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>sistci.reclassificacao</code> table reference
     */
    public Reclassificacao() {
        this("reclassificacao", null);
    }

    /**
     * Create an aliased <code>sistci.reclassificacao</code> table reference
     */
    public Reclassificacao(String alias) {
        this(alias, RECLASSIFICACAO);
    }

    private Reclassificacao(String alias, Table<ReclassificacaoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Reclassificacao(String alias, Table<ReclassificacaoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sistci.SISTCI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ReclassificacaoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RECLASSIFICACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReclassificacaoRecord> getPrimaryKey() {
        return Keys.KEY_RECLASSIFICACAO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReclassificacaoRecord>> getKeys() {
        return Arrays.<UniqueKey<ReclassificacaoRecord>>asList(Keys.KEY_RECLASSIFICACAO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ReclassificacaoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ReclassificacaoRecord, ?>>asList(Keys.FKRECLASSIFI428042, Keys.FKRECLASSIFI625325);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Reclassificacao as(String alias) {
        return new Reclassificacao(alias, this);
    }

    /**
     * Rename this table
     */
    public Reclassificacao rename(String name) {
        return new Reclassificacao(name, null);
    }
}
