/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reclassificacao extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord> {

	private static final long serialVersionUID = -193722864;

	/**
	 * The singleton instance of <code>sistci.reclassificacao</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Reclassificacao RECLASSIFICACAO = new com.github.gtmelo.sistci_api.data.tables.Reclassificacao();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord.class;
	}

	/**
	 * The column <code>sistci.reclassificacao.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.reclassificacao.grau_sigiloid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord, java.lang.Integer> GRAU_SIGILOID = createField("grau_sigiloid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.reclassificacao.operacaoid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord, java.lang.Integer> OPERACAOID = createField("operacaoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>sistci.reclassificacao</code> table reference
	 */
	public Reclassificacao() {
		this("reclassificacao", null);
	}

	/**
	 * Create an aliased <code>sistci.reclassificacao</code> table reference
	 */
	public Reclassificacao(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.Reclassificacao.RECLASSIFICACAO);
	}

	private Reclassificacao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Reclassificacao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_RECLASSIFICACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_RECLASSIFICACAO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_RECLASSIFICACAO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord, ?>>asList(com.github.gtmelo.sistci_api.data.Keys.FKRECLASSIFI428042, com.github.gtmelo.sistci_api.data.Keys.FKRECLASSIFI625325);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.Reclassificacao as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.Reclassificacao(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.Reclassificacao rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.Reclassificacao(name, null);
	}
}
