/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;


import com.github.gtmelo.sistci_api.data.Keys;
import com.github.gtmelo.sistci_api.data.Sistci;
import com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reducao extends TableImpl<ReducaoRecord> {

    private static final long serialVersionUID = 350660226;

    /**
     * The reference instance of <code>sistci.reducao</code>
     */
    public static final Reducao REDUCAO = new Reducao();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ReducaoRecord> getRecordType() {
        return ReducaoRecord.class;
    }

    /**
     * The column <code>sistci.reducao.id</code>.
     */
    public final TableField<ReducaoRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.reducao.prazoid</code>.
     */
    public final TableField<ReducaoRecord, Integer> PRAZOID = createField("prazoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>sistci.reducao.operacaoid</code>.
     */
    public final TableField<ReducaoRecord, Integer> OPERACAOID = createField("operacaoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * Create a <code>sistci.reducao</code> table reference
     */
    public Reducao() {
        this("reducao", null);
    }

    /**
     * Create an aliased <code>sistci.reducao</code> table reference
     */
    public Reducao(String alias) {
        this(alias, REDUCAO);
    }

    private Reducao(String alias, Table<ReducaoRecord> aliased) {
        this(alias, aliased, null);
    }

    private Reducao(String alias, Table<ReducaoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Sistci.SISTCI;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ReducaoRecord, Integer> getIdentity() {
        return Keys.IDENTITY_REDUCAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ReducaoRecord> getPrimaryKey() {
        return Keys.KEY_REDUCAO_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ReducaoRecord>> getKeys() {
        return Arrays.<UniqueKey<ReducaoRecord>>asList(Keys.KEY_REDUCAO_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<ReducaoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<ReducaoRecord, ?>>asList(Keys.REDUCAO_PRAZO, Keys.FKREDUCAO363962);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Reducao as(String alias) {
        return new Reducao(alias, this);
    }

    /**
     * Rename this table
     */
    public Reducao rename(String name) {
        return new Reducao(name, null);
    }
}
