/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reducao extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord> {

	private static final long serialVersionUID = 767647917;

	/**
	 * The singleton instance of <code>sistci.reducao</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Reducao REDUCAO = new com.github.gtmelo.sistci_api.data.tables.Reducao();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord.class;
	}

	/**
	 * The column <code>sistci.reducao.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.reducao.prazoid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord, java.lang.Integer> PRAZOID = createField("prazoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.reducao.operacaoid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord, java.lang.Integer> OPERACAOID = createField("operacaoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>sistci.reducao</code> table reference
	 */
	public Reducao() {
		this("reducao", null);
	}

	/**
	 * Create an aliased <code>sistci.reducao</code> table reference
	 */
	public Reducao(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.Reducao.REDUCAO);
	}

	private Reducao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord> aliased) {
		this(alias, aliased, null);
	}

	private Reducao(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_REDUCAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_REDUCAO_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_REDUCAO_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord, ?>>asList(com.github.gtmelo.sistci_api.data.Keys.REDUCAO_PRAZO, com.github.gtmelo.sistci_api.data.Keys.FKREDUCAO363962);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.Reducao as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.Reducao(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.Reducao rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.Reducao(name, null);
	}
}
