/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Status extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.StatusRecord> {

	private static final long serialVersionUID = -1820416187;

	/**
	 * The singleton instance of <code>sistci.status</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Status STATUS = new com.github.gtmelo.sistci_api.data.tables.Status();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.StatusRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.StatusRecord.class;
	}

	/**
	 * The column <code>sistci.status.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.StatusRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.status.descricao</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.StatusRecord, java.lang.String> DESCRICAO = createField("descricao", org.jooq.impl.SQLDataType.VARCHAR.length(20).nullable(false), this, "");

	/**
	 * Create a <code>sistci.status</code> table reference
	 */
	public Status() {
		this("status", null);
	}

	/**
	 * Create an aliased <code>sistci.status</code> table reference
	 */
	public Status(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.Status.STATUS);
	}

	private Status(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.StatusRecord> aliased) {
		this(alias, aliased, null);
	}

	private Status(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.StatusRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.StatusRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.StatusRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_STATUS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.StatusRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.StatusRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_STATUS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.Status as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.Status(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.Status rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.Status(name, null);
	}
}
