/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tci extends org.jooq.impl.TableImpl<com.github.gtmelo.sistci_api.data.tables.records.TciRecord> {

	private static final long serialVersionUID = 1736409723;

	/**
	 * The singleton instance of <code>sistci.tci</code>
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Tci TCI = new com.github.gtmelo.sistci_api.data.tables.Tci();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.gtmelo.sistci_api.data.tables.records.TciRecord> getRecordType() {
		return com.github.gtmelo.sistci_api.data.tables.records.TciRecord.class;
	}

	/**
	 * The column <code>sistci.tci.id</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.tci.orgaoid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, java.lang.Integer> ORGAOID = createField("orgaoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.tci.pessoaid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, java.lang.Integer> PESSOAID = createField("pessoaid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.tci.categoriaid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, java.lang.Integer> CATEGORIAID = createField("categoriaid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.tci.prazoid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, java.lang.Integer> PRAZOID = createField("prazoid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.tci.fundamento_legalid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, java.lang.Integer> FUNDAMENTO_LEGALID = createField("fundamento_legalid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.tci.grau_sigiloid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, java.lang.Integer> GRAU_SIGILOID = createField("grau_sigiloid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.tci.statusid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, java.lang.Integer> STATUSID = createField("statusid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.tci.cidicid</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, java.lang.Integer> CIDICID = createField("cidicid", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>sistci.tci.nup</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, java.lang.String> NUP = createField("nup", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * The column <code>sistci.tci.data_producao</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, java.sql.Date> DATA_PRODUCAO = createField("data_producao", org.jooq.impl.SQLDataType.DATE, this, "");

	/**
	 * The column <code>sistci.tci.tipo</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, java.lang.String> TIPO = createField("tipo", org.jooq.impl.SQLDataType.VARCHAR.length(254).nullable(false), this, "");

	/**
	 * The column <code>sistci.tci.razao_classificacao</code>.
	 */
	public final org.jooq.TableField<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, java.lang.String> RAZAO_CLASSIFICACAO = createField("razao_classificacao", org.jooq.impl.SQLDataType.VARCHAR.length(254).nullable(false), this, "");

	/**
	 * Create a <code>sistci.tci</code> table reference
	 */
	public Tci() {
		this("tci", null);
	}

	/**
	 * Create an aliased <code>sistci.tci</code> table reference
	 */
	public Tci(java.lang.String alias) {
		this(alias, com.github.gtmelo.sistci_api.data.tables.Tci.TCI);
	}

	private Tci(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.TciRecord> aliased) {
		this(alias, aliased, null);
	}

	private Tci(java.lang.String alias, org.jooq.Table<com.github.gtmelo.sistci_api.data.tables.records.TciRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.gtmelo.sistci_api.data.Sistci.SISTCI, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, java.lang.Integer> getIdentity() {
		return com.github.gtmelo.sistci_api.data.Keys.IDENTITY_TCI;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.TciRecord> getPrimaryKey() {
		return com.github.gtmelo.sistci_api.data.Keys.KEY_TCI_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.TciRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.github.gtmelo.sistci_api.data.tables.records.TciRecord>>asList(com.github.gtmelo.sistci_api.data.Keys.KEY_TCI_PRIMARY, com.github.gtmelo.sistci_api.data.Keys.KEY_TCI_NUP);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.github.gtmelo.sistci_api.data.tables.records.TciRecord, ?>>asList(com.github.gtmelo.sistci_api.data.Keys.ORGAO_TCI, com.github.gtmelo.sistci_api.data.Keys.PESSOA_TCI, com.github.gtmelo.sistci_api.data.Keys.TCI_CATEGORIA, com.github.gtmelo.sistci_api.data.Keys.TCI_PRAZO, com.github.gtmelo.sistci_api.data.Keys.TCI_FUNDAMENTO_LEGAL, com.github.gtmelo.sistci_api.data.Keys.TCI_GRAU_SIGILO, com.github.gtmelo.sistci_api.data.Keys.TCI_STATUS, com.github.gtmelo.sistci_api.data.Keys.TCI_CIDIC);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.gtmelo.sistci_api.data.tables.Tci as(java.lang.String alias) {
		return new com.github.gtmelo.sistci_api.data.tables.Tci(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.gtmelo.sistci_api.data.tables.Tci rename(java.lang.String name) {
		return new com.github.gtmelo.sistci_api.data.tables.Tci(name, null);
	}
}
