/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;


import com.github.gtmelo.sistci_api.data.tables.AutoridadeRatificadora;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AutoridadeRatificadoraRecord extends UpdatableRecordImpl<AutoridadeRatificadoraRecord> implements Record3<Integer, String, String> {

    private static final long serialVersionUID = 752078507;

    /**
     * Setter for <code>sistci.autoridade_ratificadora.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sistci.autoridade_ratificadora.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistci.autoridade_ratificadora.nome</code>.
     */
    public void setNome(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sistci.autoridade_ratificadora.nome</code>.
     */
    public String getNome() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sistci.autoridade_ratificadora.cargo</code>.
     */
    public void setCargo(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sistci.autoridade_ratificadora.cargo</code>.
     */
    public String getCargo() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return AutoridadeRatificadora.AUTORIDADE_RATIFICADORA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return AutoridadeRatificadora.AUTORIDADE_RATIFICADORA.NOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return AutoridadeRatificadora.AUTORIDADE_RATIFICADORA.CARGO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCargo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutoridadeRatificadoraRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutoridadeRatificadoraRecord value2(String value) {
        setNome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutoridadeRatificadoraRecord value3(String value) {
        setCargo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AutoridadeRatificadoraRecord values(Integer value1, String value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AutoridadeRatificadoraRecord
     */
    public AutoridadeRatificadoraRecord() {
        super(AutoridadeRatificadora.AUTORIDADE_RATIFICADORA);
    }

    /**
     * Create a detached, initialised AutoridadeRatificadoraRecord
     */
    public AutoridadeRatificadoraRecord(Integer id, String nome, String cargo) {
        super(AutoridadeRatificadora.AUTORIDADE_RATIFICADORA);

        set(0, id);
        set(1, nome);
        set(2, cargo);
    }
}
