/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;


import com.github.gtmelo.sistci_api.data.tables.Cargo;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CargoRecord extends UpdatableRecordImpl<CargoRecord> implements Record3<Integer, String, Integer> {

    private static final long serialVersionUID = -683092421;

    /**
     * Setter for <code>sistci.cargo.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sistci.cargo.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistci.cargo.descricao</code>.
     */
    public void setDescricao(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>sistci.cargo.descricao</code>.
     */
    public String getDescricao() {
        return (String) get(1);
    }

    /**
     * Setter for <code>sistci.cargo.orgaoid</code>.
     */
    public void setOrgaoid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sistci.cargo.orgaoid</code>.
     */
    public Integer getOrgaoid() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, String, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Cargo.CARGO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Cargo.CARGO.DESCRICAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Cargo.CARGO.ORGAOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDescricao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOrgaoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CargoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CargoRecord value2(String value) {
        setDescricao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CargoRecord value3(Integer value) {
        setOrgaoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CargoRecord values(Integer value1, String value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CargoRecord
     */
    public CargoRecord() {
        super(Cargo.CARGO);
    }

    /**
     * Create a detached, initialised CargoRecord
     */
    public CargoRecord(Integer id, String descricao, Integer orgaoid) {
        super(Cargo.CARGO);

        set(0, id);
        set(1, descricao);
        set(2, orgaoid);
    }
}
