/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassificacaoRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1876782609;

	/**
	 * Setter for <code>sistci.classificacao.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sistci.classificacao.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sistci.classificacao.autoridade_ratificadoraid</code>.
	 */
	public void setAutoridadeRatificadoraid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sistci.classificacao.autoridade_ratificadoraid</code>.
	 */
	public java.lang.Integer getAutoridadeRatificadoraid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>sistci.classificacao.operacaoid</code>.
	 */
	public void setOperacaoid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sistci.classificacao.operacaoid</code>.
	 */
	public java.lang.Integer getOperacaoid() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.gtmelo.sistci_api.data.tables.Classificacao.CLASSIFICACAO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.github.gtmelo.sistci_api.data.tables.Classificacao.CLASSIFICACAO.AUTORIDADE_RATIFICADORAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.github.gtmelo.sistci_api.data.tables.Classificacao.CLASSIFICACAO.OPERACAOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getAutoridadeRatificadoraid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getOperacaoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClassificacaoRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClassificacaoRecord value2(java.lang.Integer value) {
		setAutoridadeRatificadoraid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClassificacaoRecord value3(java.lang.Integer value) {
		setOperacaoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClassificacaoRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ClassificacaoRecord
	 */
	public ClassificacaoRecord() {
		super(com.github.gtmelo.sistci_api.data.tables.Classificacao.CLASSIFICACAO);
	}

	/**
	 * Create a detached, initialised ClassificacaoRecord
	 */
	public ClassificacaoRecord(java.lang.Integer id, java.lang.Integer autoridadeRatificadoraid, java.lang.Integer operacaoid) {
		super(com.github.gtmelo.sistci_api.data.tables.Classificacao.CLASSIFICACAO);

		setValue(0, id);
		setValue(1, autoridadeRatificadoraid);
		setValue(2, operacaoid);
	}
}
