/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;


import com.github.gtmelo.sistci_api.data.tables.Classificacao;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassificacaoRecord extends UpdatableRecordImpl<ClassificacaoRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 424863895;

    /**
     * Setter for <code>sistci.classificacao.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sistci.classificacao.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistci.classificacao.autoridade_ratificadoraid</code>.
     */
    public void setAutoridadeRatificadoraid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sistci.classificacao.autoridade_ratificadoraid</code>.
     */
    public Integer getAutoridadeRatificadoraid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sistci.classificacao.operacaoid</code>.
     */
    public void setOperacaoid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sistci.classificacao.operacaoid</code>.
     */
    public Integer getOperacaoid() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Classificacao.CLASSIFICACAO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Classificacao.CLASSIFICACAO.AUTORIDADE_RATIFICADORAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Classificacao.CLASSIFICACAO.OPERACAOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAutoridadeRatificadoraid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOperacaoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassificacaoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassificacaoRecord value2(Integer value) {
        setAutoridadeRatificadoraid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassificacaoRecord value3(Integer value) {
        setOperacaoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ClassificacaoRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ClassificacaoRecord
     */
    public ClassificacaoRecord() {
        super(Classificacao.CLASSIFICACAO);
    }

    /**
     * Create a detached, initialised ClassificacaoRecord
     */
    public ClassificacaoRecord(Integer id, Integer autoridadeRatificadoraid, Integer operacaoid) {
        super(Classificacao.CLASSIFICACAO);

        set(0, id);
        set(1, autoridadeRatificadoraid);
        set(2, operacaoid);
    }
}
