/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CpadsPessoaRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.gtmelo.sistci_api.data.tables.records.CpadsPessoaRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1613466447;

	/**
	 * Setter for <code>sistci.cpads_pessoa.cpadsid</code>.
	 */
	public void setCpadsid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sistci.cpads_pessoa.cpadsid</code>.
	 */
	public java.lang.Integer getCpadsid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sistci.cpads_pessoa.pessoaid</code>.
	 */
	public void setPessoaid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sistci.cpads_pessoa.pessoaid</code>.
	 */
	public java.lang.Integer getPessoaid() {
		return (java.lang.Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Integer, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.gtmelo.sistci_api.data.tables.CpadsPessoa.CPADS_PESSOA.CPADSID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.github.gtmelo.sistci_api.data.tables.CpadsPessoa.CPADS_PESSOA.PESSOAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getCpadsid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getPessoaid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CpadsPessoaRecord value1(java.lang.Integer value) {
		setCpadsid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CpadsPessoaRecord value2(java.lang.Integer value) {
		setPessoaid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CpadsPessoaRecord values(java.lang.Integer value1, java.lang.Integer value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CpadsPessoaRecord
	 */
	public CpadsPessoaRecord() {
		super(com.github.gtmelo.sistci_api.data.tables.CpadsPessoa.CPADS_PESSOA);
	}

	/**
	 * Create a detached, initialised CpadsPessoaRecord
	 */
	public CpadsPessoaRecord(java.lang.Integer cpadsid, java.lang.Integer pessoaid) {
		super(com.github.gtmelo.sistci_api.data.tables.CpadsPessoa.CPADS_PESSOA);

		setValue(0, cpadsid);
		setValue(1, pessoaid);
	}
}
