/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;


import com.github.gtmelo.sistci_api.data.tables.CpadsPessoa;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CpadsPessoaRecord extends UpdatableRecordImpl<CpadsPessoaRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = -1742050704;

    /**
     * Setter for <code>sistci.cpads_pessoa.cpadsid</code>.
     */
    public void setCpadsid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sistci.cpads_pessoa.cpadsid</code>.
     */
    public Integer getCpadsid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistci.cpads_pessoa.pessoaid</code>.
     */
    public void setPessoaid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sistci.cpads_pessoa.pessoaid</code>.
     */
    public Integer getPessoaid() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return CpadsPessoa.CPADS_PESSOA.CPADSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return CpadsPessoa.CPADS_PESSOA.PESSOAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getCpadsid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPessoaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CpadsPessoaRecord value1(Integer value) {
        setCpadsid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CpadsPessoaRecord value2(Integer value) {
        setPessoaid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CpadsPessoaRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CpadsPessoaRecord
     */
    public CpadsPessoaRecord() {
        super(CpadsPessoa.CPADS_PESSOA);
    }

    /**
     * Create a detached, initialised CpadsPessoaRecord
     */
    public CpadsPessoaRecord(Integer cpadsid, Integer pessoaid) {
        super(CpadsPessoa.CPADS_PESSOA);

        set(0, cpadsid);
        set(1, pessoaid);
    }
}
