/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CpadsRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Date> {

	private static final long serialVersionUID = 237406843;

	/**
	 * Setter for <code>sistci.cpads.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sistci.cpads.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sistci.cpads.orgaoid</code>.
	 */
	public void setOrgaoid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sistci.cpads.orgaoid</code>.
	 */
	public java.lang.Integer getOrgaoid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>sistci.cpads.portaria_nomeacao</code>.
	 */
	public void setPortariaNomeacao(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sistci.cpads.portaria_nomeacao</code>.
	 */
	public java.lang.String getPortariaNomeacao() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>sistci.cpads.data_formacao</code>.
	 */
	public void setDataFormacao(java.sql.Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sistci.cpads.data_formacao</code>.
	 */
	public java.sql.Date getDataFormacao() {
		return (java.sql.Date) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Date> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Date> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.gtmelo.sistci_api.data.tables.Cpads.CPADS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.github.gtmelo.sistci_api.data.tables.Cpads.CPADS.ORGAOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.github.gtmelo.sistci_api.data.tables.Cpads.CPADS.PORTARIA_NOMEACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field4() {
		return com.github.gtmelo.sistci_api.data.tables.Cpads.CPADS.DATA_FORMACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getOrgaoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getPortariaNomeacao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value4() {
		return getDataFormacao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CpadsRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CpadsRecord value2(java.lang.Integer value) {
		setOrgaoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CpadsRecord value3(java.lang.String value) {
		setPortariaNomeacao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CpadsRecord value4(java.sql.Date value) {
		setDataFormacao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CpadsRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.String value3, java.sql.Date value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CpadsRecord
	 */
	public CpadsRecord() {
		super(com.github.gtmelo.sistci_api.data.tables.Cpads.CPADS);
	}

	/**
	 * Create a detached, initialised CpadsRecord
	 */
	public CpadsRecord(java.lang.Integer id, java.lang.Integer orgaoid, java.lang.String portariaNomeacao, java.sql.Date dataFormacao) {
		super(com.github.gtmelo.sistci_api.data.tables.Cpads.CPADS);

		setValue(0, id);
		setValue(1, orgaoid);
		setValue(2, portariaNomeacao);
		setValue(3, dataFormacao);
	}
}
