/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FundamentoLegalRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.gtmelo.sistci_api.data.tables.records.FundamentoLegalRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = -123561418;

	/**
	 * Setter for <code>sistci.fundamento_legal.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sistci.fundamento_legal.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sistci.fundamento_legal.descricao</code>.
	 */
	public void setDescricao(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sistci.fundamento_legal.descricao</code>.
	 */
	public java.lang.String getDescricao() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.gtmelo.sistci_api.data.tables.FundamentoLegal.FUNDAMENTO_LEGAL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.github.gtmelo.sistci_api.data.tables.FundamentoLegal.FUNDAMENTO_LEGAL.DESCRICAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getDescricao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FundamentoLegalRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FundamentoLegalRecord value2(java.lang.String value) {
		setDescricao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public FundamentoLegalRecord values(java.lang.Integer value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached FundamentoLegalRecord
	 */
	public FundamentoLegalRecord() {
		super(com.github.gtmelo.sistci_api.data.tables.FundamentoLegal.FUNDAMENTO_LEGAL);
	}

	/**
	 * Create a detached, initialised FundamentoLegalRecord
	 */
	public FundamentoLegalRecord(java.lang.Integer id, java.lang.String descricao) {
		super(com.github.gtmelo.sistci_api.data.tables.FundamentoLegal.FUNDAMENTO_LEGAL);

		setValue(0, id);
		setValue(1, descricao);
	}
}
