/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GrauSigiloRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord> implements org.jooq.Record4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = -1195939497;

	/**
	 * Setter for <code>sistci.grau_sigilo.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sistci.grau_sigilo.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sistci.grau_sigilo.abreviacao</code>.
	 */
	public void setAbreviacao(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sistci.grau_sigilo.abreviacao</code>.
	 */
	public java.lang.String getAbreviacao() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sistci.grau_sigilo.descricao</code>.
	 */
	public void setDescricao(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sistci.grau_sigilo.descricao</code>.
	 */
	public java.lang.String getDescricao() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>sistci.grau_sigilo.permite_prorrogacao</code>.
	 */
	public void setPermiteProrrogacao(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sistci.grau_sigilo.permite_prorrogacao</code>.
	 */
	public java.lang.Integer getPermiteProrrogacao() {
		return (java.lang.Integer) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.gtmelo.sistci_api.data.tables.GrauSigilo.GRAU_SIGILO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.github.gtmelo.sistci_api.data.tables.GrauSigilo.GRAU_SIGILO.ABREVIACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.github.gtmelo.sistci_api.data.tables.GrauSigilo.GRAU_SIGILO.DESCRICAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.github.gtmelo.sistci_api.data.tables.GrauSigilo.GRAU_SIGILO.PERMITE_PRORROGACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getAbreviacao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDescricao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getPermiteProrrogacao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GrauSigiloRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GrauSigiloRecord value2(java.lang.String value) {
		setAbreviacao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GrauSigiloRecord value3(java.lang.String value) {
		setDescricao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GrauSigiloRecord value4(java.lang.Integer value) {
		setPermiteProrrogacao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public GrauSigiloRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.Integer value4) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GrauSigiloRecord
	 */
	public GrauSigiloRecord() {
		super(com.github.gtmelo.sistci_api.data.tables.GrauSigilo.GRAU_SIGILO);
	}

	/**
	 * Create a detached, initialised GrauSigiloRecord
	 */
	public GrauSigiloRecord(java.lang.Integer id, java.lang.String abreviacao, java.lang.String descricao, java.lang.Integer permiteProrrogacao) {
		super(com.github.gtmelo.sistci_api.data.tables.GrauSigilo.GRAU_SIGILO);

		setValue(0, id);
		setValue(1, abreviacao);
		setValue(2, descricao);
		setValue(3, permiteProrrogacao);
	}
}
