/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OperacaoRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Date, java.lang.String> {

	private static final long serialVersionUID = 46858693;

	/**
	 * Setter for <code>sistci.operacao.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sistci.operacao.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sistci.operacao.statusid</code>.
	 */
	public void setStatusid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sistci.operacao.statusid</code>.
	 */
	public java.lang.Integer getStatusid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>sistci.operacao.pessoaid</code>.
	 */
	public void setPessoaid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sistci.operacao.pessoaid</code>.
	 */
	public java.lang.Integer getPessoaid() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>sistci.operacao.autoridadeid</code>.
	 */
	public void setAutoridadeid(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sistci.operacao.autoridadeid</code>.
	 */
	public java.lang.Integer getAutoridadeid() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>sistci.operacao.tciid</code>.
	 */
	public void setTciid(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sistci.operacao.tciid</code>.
	 */
	public java.lang.Integer getTciid() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>sistci.operacao.data</code>.
	 */
	public void setData(java.sql.Date value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sistci.operacao.data</code>.
	 */
	public java.sql.Date getData() {
		return (java.sql.Date) getValue(5);
	}

	/**
	 * Setter for <code>sistci.operacao.imagem</code>.
	 */
	public void setImagem(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sistci.operacao.imagem</code>.
	 */
	public java.lang.String getImagem() {
		return (java.lang.String) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Date, java.lang.String> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.sql.Date, java.lang.String> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.gtmelo.sistci_api.data.tables.Operacao.OPERACAO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.github.gtmelo.sistci_api.data.tables.Operacao.OPERACAO.STATUSID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.github.gtmelo.sistci_api.data.tables.Operacao.OPERACAO.PESSOAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.github.gtmelo.sistci_api.data.tables.Operacao.OPERACAO.AUTORIDADEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.github.gtmelo.sistci_api.data.tables.Operacao.OPERACAO.TCIID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field6() {
		return com.github.gtmelo.sistci_api.data.tables.Operacao.OPERACAO.DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.github.gtmelo.sistci_api.data.tables.Operacao.OPERACAO.IMAGEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getStatusid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getPessoaid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getAutoridadeid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getTciid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value6() {
		return getData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getImagem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OperacaoRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OperacaoRecord value2(java.lang.Integer value) {
		setStatusid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OperacaoRecord value3(java.lang.Integer value) {
		setPessoaid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OperacaoRecord value4(java.lang.Integer value) {
		setAutoridadeid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OperacaoRecord value5(java.lang.Integer value) {
		setTciid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OperacaoRecord value6(java.sql.Date value) {
		setData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OperacaoRecord value7(java.lang.String value) {
		setImagem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OperacaoRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.Integer value5, java.sql.Date value6, java.lang.String value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached OperacaoRecord
	 */
	public OperacaoRecord() {
		super(com.github.gtmelo.sistci_api.data.tables.Operacao.OPERACAO);
	}

	/**
	 * Create a detached, initialised OperacaoRecord
	 */
	public OperacaoRecord(java.lang.Integer id, java.lang.Integer statusid, java.lang.Integer pessoaid, java.lang.Integer autoridadeid, java.lang.Integer tciid, java.sql.Date data, java.lang.String imagem) {
		super(com.github.gtmelo.sistci_api.data.tables.Operacao.OPERACAO);

		setValue(0, id);
		setValue(1, statusid);
		setValue(2, pessoaid);
		setValue(3, autoridadeid);
		setValue(4, tciid);
		setValue(5, data);
		setValue(6, imagem);
	}
}
