/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;


import com.github.gtmelo.sistci_api.data.tables.Operacao;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OperacaoRecord extends UpdatableRecordImpl<OperacaoRecord> implements Record7<Integer, Integer, Integer, Integer, Integer, Date, String> {

    private static final long serialVersionUID = 1327190022;

    /**
     * Setter for <code>sistci.operacao.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sistci.operacao.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistci.operacao.statusid</code>.
     */
    public void setStatusid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sistci.operacao.statusid</code>.
     */
    public Integer getStatusid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sistci.operacao.pessoaid</code>.
     */
    public void setPessoaid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sistci.operacao.pessoaid</code>.
     */
    public Integer getPessoaid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sistci.operacao.autoridadeid</code>.
     */
    public void setAutoridadeid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sistci.operacao.autoridadeid</code>.
     */
    public Integer getAutoridadeid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>sistci.operacao.tciid</code>.
     */
    public void setTciid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>sistci.operacao.tciid</code>.
     */
    public Integer getTciid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>sistci.operacao.data</code>.
     */
    public void setData(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>sistci.operacao.data</code>.
     */
    public Date getData() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>sistci.operacao.imagem</code>.
     */
    public void setImagem(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sistci.operacao.imagem</code>.
     */
    public String getImagem() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Date, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Date, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Operacao.OPERACAO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Operacao.OPERACAO.STATUSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Operacao.OPERACAO.PESSOAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Operacao.OPERACAO.AUTORIDADEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Operacao.OPERACAO.TCIID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return Operacao.OPERACAO.DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Operacao.OPERACAO.IMAGEM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStatusid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPessoaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getAutoridadeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getTciid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getImagem();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperacaoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperacaoRecord value2(Integer value) {
        setStatusid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperacaoRecord value3(Integer value) {
        setPessoaid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperacaoRecord value4(Integer value) {
        setAutoridadeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperacaoRecord value5(Integer value) {
        setTciid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperacaoRecord value6(Date value) {
        setData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperacaoRecord value7(String value) {
        setImagem(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OperacaoRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Date value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OperacaoRecord
     */
    public OperacaoRecord() {
        super(Operacao.OPERACAO);
    }

    /**
     * Create a detached, initialised OperacaoRecord
     */
    public OperacaoRecord(Integer id, Integer statusid, Integer pessoaid, Integer autoridadeid, Integer tciid, Date data, String imagem) {
        super(Operacao.OPERACAO);

        set(0, id);
        set(1, statusid);
        set(2, pessoaid);
        set(3, autoridadeid);
        set(4, tciid);
        set(5, data);
        set(6, imagem);
    }
}
