/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgaoRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1588200551;

	/**
	 * Setter for <code>sistci.orgao.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sistci.orgao.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sistci.orgao.sigla</code>.
	 */
	public void setSigla(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sistci.orgao.sigla</code>.
	 */
	public java.lang.String getSigla() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sistci.orgao.nome</code>.
	 */
	public void setNome(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sistci.orgao.nome</code>.
	 */
	public java.lang.String getNome() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>sistci.orgao.telefone</code>.
	 */
	public void setTelefone(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sistci.orgao.telefone</code>.
	 */
	public java.lang.String getTelefone() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>sistci.orgao.endereco</code>.
	 */
	public void setEndereco(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sistci.orgao.endereco</code>.
	 */
	public java.lang.String getEndereco() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>sistci.orgao.emailid</code>.
	 */
	public void setEmailid(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sistci.orgao.emailid</code>.
	 */
	public java.lang.Integer getEmailid() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>sistci.orgao.orgao_superiorid</code>.
	 */
	public void setOrgaoSuperiorid(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sistci.orgao.orgao_superiorid</code>.
	 */
	public java.lang.Integer getOrgaoSuperiorid() {
		return (java.lang.Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.gtmelo.sistci_api.data.tables.Orgao.ORGAO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.github.gtmelo.sistci_api.data.tables.Orgao.ORGAO.SIGLA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.github.gtmelo.sistci_api.data.tables.Orgao.ORGAO.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.github.gtmelo.sistci_api.data.tables.Orgao.ORGAO.TELEFONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.github.gtmelo.sistci_api.data.tables.Orgao.ORGAO.ENDERECO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.github.gtmelo.sistci_api.data.tables.Orgao.ORGAO.EMAILID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.github.gtmelo.sistci_api.data.tables.Orgao.ORGAO.ORGAO_SUPERIORID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSigla();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getNome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTelefone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getEndereco();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getEmailid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getOrgaoSuperiorid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrgaoRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrgaoRecord value2(java.lang.String value) {
		setSigla(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrgaoRecord value3(java.lang.String value) {
		setNome(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrgaoRecord value4(java.lang.String value) {
		setTelefone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrgaoRecord value5(java.lang.String value) {
		setEndereco(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrgaoRecord value6(java.lang.Integer value) {
		setEmailid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrgaoRecord value7(java.lang.Integer value) {
		setOrgaoSuperiorid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrgaoRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.Integer value6, java.lang.Integer value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached OrgaoRecord
	 */
	public OrgaoRecord() {
		super(com.github.gtmelo.sistci_api.data.tables.Orgao.ORGAO);
	}

	/**
	 * Create a detached, initialised OrgaoRecord
	 */
	public OrgaoRecord(java.lang.Integer id, java.lang.String sigla, java.lang.String nome, java.lang.String telefone, java.lang.String endereco, java.lang.Integer emailid, java.lang.Integer orgaoSuperiorid) {
		super(com.github.gtmelo.sistci_api.data.tables.Orgao.ORGAO);

		setValue(0, id);
		setValue(1, sigla);
		setValue(2, nome);
		setValue(3, telefone);
		setValue(4, endereco);
		setValue(5, emailid);
		setValue(6, orgaoSuperiorid);
	}
}
