/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;


import com.github.gtmelo.sistci_api.data.tables.Orgao;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgaoRecord extends UpdatableRecordImpl<OrgaoRecord> implements Record7<Integer, Integer, Integer, String, String, String, String> {

    private static final long serialVersionUID = 308909992;

    /**
     * Setter for <code>sistci.orgao.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sistci.orgao.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistci.orgao.organizacaoid</code>.
     */
    public void setOrganizacaoid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sistci.orgao.organizacaoid</code>.
     */
    public Integer getOrganizacaoid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sistci.orgao.emailid</code>.
     */
    public void setEmailid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sistci.orgao.emailid</code>.
     */
    public Integer getEmailid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sistci.orgao.sigla</code>.
     */
    public void setSigla(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>sistci.orgao.sigla</code>.
     */
    public String getSigla() {
        return (String) get(3);
    }

    /**
     * Setter for <code>sistci.orgao.nome</code>.
     */
    public void setNome(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>sistci.orgao.nome</code>.
     */
    public String getNome() {
        return (String) get(4);
    }

    /**
     * Setter for <code>sistci.orgao.telefone</code>.
     */
    public void setTelefone(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sistci.orgao.telefone</code>.
     */
    public String getTelefone() {
        return (String) get(5);
    }

    /**
     * Setter for <code>sistci.orgao.endereco</code>.
     */
    public void setEndereco(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>sistci.orgao.endereco</code>.
     */
    public String getEndereco() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, String, String, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Orgao.ORGAO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Orgao.ORGAO.ORGANIZACAOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Orgao.ORGAO.EMAILID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Orgao.ORGAO.SIGLA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Orgao.ORGAO.NOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Orgao.ORGAO.TELEFONE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Orgao.ORGAO.ENDERECO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrganizacaoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getEmailid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSigla();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTelefone();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getEndereco();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgaoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgaoRecord value2(Integer value) {
        setOrganizacaoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgaoRecord value3(Integer value) {
        setEmailid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgaoRecord value4(String value) {
        setSigla(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgaoRecord value5(String value) {
        setNome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgaoRecord value6(String value) {
        setTelefone(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgaoRecord value7(String value) {
        setEndereco(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrgaoRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrgaoRecord
     */
    public OrgaoRecord() {
        super(Orgao.ORGAO);
    }

    /**
     * Create a detached, initialised OrgaoRecord
     */
    public OrgaoRecord(Integer id, Integer organizacaoid, Integer emailid, String sigla, String nome, String telefone, String endereco) {
        super(Orgao.ORGAO);

        set(0, id);
        set(1, organizacaoid);
        set(2, emailid);
        set(3, sigla);
        set(4, nome);
        set(5, telefone);
        set(6, endereco);
    }
}
