/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrganizacaoRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1749749168;

	/**
	 * Setter for <code>sistci.organizacao.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sistci.organizacao.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sistci.organizacao.sigla</code>.
	 */
	public void setSigla(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sistci.organizacao.sigla</code>.
	 */
	public java.lang.String getSigla() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sistci.organizacao.nome</code>.
	 */
	public void setNome(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sistci.organizacao.nome</code>.
	 */
	public java.lang.String getNome() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.gtmelo.sistci_api.data.tables.Organizacao.ORGANIZACAO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.github.gtmelo.sistci_api.data.tables.Organizacao.ORGANIZACAO.SIGLA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.github.gtmelo.sistci_api.data.tables.Organizacao.ORGANIZACAO.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getSigla();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getNome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganizacaoRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganizacaoRecord value2(java.lang.String value) {
		setSigla(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganizacaoRecord value3(java.lang.String value) {
		setNome(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OrganizacaoRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached OrganizacaoRecord
	 */
	public OrganizacaoRecord() {
		super(com.github.gtmelo.sistci_api.data.tables.Organizacao.ORGANIZACAO);
	}

	/**
	 * Create a detached, initialised OrganizacaoRecord
	 */
	public OrganizacaoRecord(java.lang.Integer id, java.lang.String sigla, java.lang.String nome) {
		super(com.github.gtmelo.sistci_api.data.tables.Organizacao.ORGANIZACAO);

		setValue(0, id);
		setValue(1, sigla);
		setValue(2, nome);
	}
}
