/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PessoaRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.gtmelo.sistci_api.data.tables.records.PessoaRecord> implements org.jooq.Record8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 1215670993;

	/**
	 * Setter for <code>sistci.pessoa.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sistci.pessoa.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sistci.pessoa.cpf</code>.
	 */
	public void setCpf(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sistci.pessoa.cpf</code>.
	 */
	public java.lang.String getCpf() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sistci.pessoa.matricula_siape</code>.
	 */
	public void setMatriculaSiape(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sistci.pessoa.matricula_siape</code>.
	 */
	public java.lang.String getMatriculaSiape() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>sistci.pessoa.nome</code>.
	 */
	public void setNome(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sistci.pessoa.nome</code>.
	 */
	public java.lang.String getNome() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>sistci.pessoa.senhaHash</code>.
	 */
	public void setSenhahash(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sistci.pessoa.senhaHash</code>.
	 */
	public java.lang.String getSenhahash() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>sistci.pessoa.emailid</code>.
	 */
	public void setEmailid(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sistci.pessoa.emailid</code>.
	 */
	public java.lang.Integer getEmailid() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>sistci.pessoa.cargoid</code>.
	 */
	public void setCargoid(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sistci.pessoa.cargoid</code>.
	 */
	public java.lang.Integer getCargoid() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>sistci.pessoa.orgaoid</code>.
	 */
	public void setOrgaoid(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>sistci.pessoa.orgaoid</code>.
	 */
	public java.lang.Integer getOrgaoid() {
		return (java.lang.Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row8<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.gtmelo.sistci_api.data.tables.Pessoa.PESSOA.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.github.gtmelo.sistci_api.data.tables.Pessoa.PESSOA.CPF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.github.gtmelo.sistci_api.data.tables.Pessoa.PESSOA.MATRICULA_SIAPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.github.gtmelo.sistci_api.data.tables.Pessoa.PESSOA.NOME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.github.gtmelo.sistci_api.data.tables.Pessoa.PESSOA.SENHAHASH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.github.gtmelo.sistci_api.data.tables.Pessoa.PESSOA.EMAILID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.github.gtmelo.sistci_api.data.tables.Pessoa.PESSOA.CARGOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return com.github.gtmelo.sistci_api.data.tables.Pessoa.PESSOA.ORGAOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getCpf();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getMatriculaSiape();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getNome();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getSenhahash();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getEmailid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getCargoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getOrgaoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PessoaRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PessoaRecord value2(java.lang.String value) {
		setCpf(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PessoaRecord value3(java.lang.String value) {
		setMatriculaSiape(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PessoaRecord value4(java.lang.String value) {
		setNome(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PessoaRecord value5(java.lang.String value) {
		setSenhahash(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PessoaRecord value6(java.lang.Integer value) {
		setEmailid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PessoaRecord value7(java.lang.Integer value) {
		setCargoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PessoaRecord value8(java.lang.Integer value) {
		setOrgaoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PessoaRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.Integer value6, java.lang.Integer value7, java.lang.Integer value8) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PessoaRecord
	 */
	public PessoaRecord() {
		super(com.github.gtmelo.sistci_api.data.tables.Pessoa.PESSOA);
	}

	/**
	 * Create a detached, initialised PessoaRecord
	 */
	public PessoaRecord(java.lang.Integer id, java.lang.String cpf, java.lang.String matriculaSiape, java.lang.String nome, java.lang.String senhahash, java.lang.Integer emailid, java.lang.Integer cargoid, java.lang.Integer orgaoid) {
		super(com.github.gtmelo.sistci_api.data.tables.Pessoa.PESSOA);

		setValue(0, id);
		setValue(1, cpf);
		setValue(2, matriculaSiape);
		setValue(3, nome);
		setValue(4, senhahash);
		setValue(5, emailid);
		setValue(6, cargoid);
		setValue(7, orgaoid);
	}
}
