/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;


import com.github.gtmelo.sistci_api.data.tables.Pessoa;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PessoaRecord extends UpdatableRecordImpl<PessoaRecord> implements Record6<Integer, Integer, Integer, Integer, Integer, String> {

    private static final long serialVersionUID = 807490954;

    /**
     * Setter for <code>sistci.pessoa.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sistci.pessoa.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistci.pessoa.emailid</code>.
     */
    public void setEmailid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sistci.pessoa.emailid</code>.
     */
    public Integer getEmailid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sistci.pessoa.orgaoid</code>.
     */
    public void setOrgaoid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sistci.pessoa.orgaoid</code>.
     */
    public Integer getOrgaoid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sistci.pessoa.cargoid</code>.
     */
    public void setCargoid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sistci.pessoa.cargoid</code>.
     */
    public Integer getCargoid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>sistci.pessoa.matricula_siape</code>.
     */
    public void setMatriculaSiape(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>sistci.pessoa.matricula_siape</code>.
     */
    public Integer getMatriculaSiape() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>sistci.pessoa.nome</code>.
     */
    public void setNome(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>sistci.pessoa.nome</code>.
     */
    public String getNome() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Pessoa.PESSOA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Pessoa.PESSOA.EMAILID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Pessoa.PESSOA.ORGAOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Pessoa.PESSOA.CARGOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Pessoa.PESSOA.MATRICULA_SIAPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Pessoa.PESSOA.NOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getEmailid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOrgaoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCargoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getMatriculaSiape();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getNome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value2(Integer value) {
        setEmailid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value3(Integer value) {
        setOrgaoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value4(Integer value) {
        setCargoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value5(Integer value) {
        setMatriculaSiape(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord value6(String value) {
        setNome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PessoaRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PessoaRecord
     */
    public PessoaRecord() {
        super(Pessoa.PESSOA);
    }

    /**
     * Create a detached, initialised PessoaRecord
     */
    public PessoaRecord(Integer id, Integer emailid, Integer orgaoid, Integer cargoid, Integer matriculaSiape, String nome) {
        super(Pessoa.PESSOA);

        set(0, id);
        set(1, emailid);
        set(2, orgaoid);
        set(3, cargoid);
        set(4, matriculaSiape);
        set(5, nome);
    }
}
