/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;


import com.github.gtmelo.sistci_api.data.tables.Prazo;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrazoRecord extends UpdatableRecordImpl<PrazoRecord> implements Record3<Integer, Date, String> {

    private static final long serialVersionUID = -1704099670;

    /**
     * Setter for <code>sistci.prazo.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sistci.prazo.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistci.prazo.data</code>.
     */
    public void setData(Date value) {
        set(1, value);
    }

    /**
     * Getter for <code>sistci.prazo.data</code>.
     */
    public Date getData() {
        return (Date) get(1);
    }

    /**
     * Setter for <code>sistci.prazo.evento</code>.
     */
    public void setEvento(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>sistci.prazo.evento</code>.
     */
    public String getEvento() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Date, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Date, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Prazo.PRAZO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field2() {
        return Prazo.PRAZO.DATA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Prazo.PRAZO.EVENTO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value2() {
        return getData();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEvento();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrazoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrazoRecord value2(Date value) {
        setData(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrazoRecord value3(String value) {
        setEvento(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PrazoRecord values(Integer value1, Date value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PrazoRecord
     */
    public PrazoRecord() {
        super(Prazo.PRAZO);
    }

    /**
     * Create a detached, initialised PrazoRecord
     */
    public PrazoRecord(Integer id, Date data, String evento) {
        super(Prazo.PRAZO);

        set(0, id);
        set(1, data);
        set(2, evento);
    }
}
