/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PrazoRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord> implements org.jooq.Record3<java.lang.Integer, java.sql.Date, java.lang.String> {

	private static final long serialVersionUID = -1228065047;

	/**
	 * Setter for <code>sistci.prazo.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sistci.prazo.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sistci.prazo.data</code>.
	 */
	public void setData(java.sql.Date value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sistci.prazo.data</code>.
	 */
	public java.sql.Date getData() {
		return (java.sql.Date) getValue(1);
	}

	/**
	 * Setter for <code>sistci.prazo.evento</code>.
	 */
	public void setEvento(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sistci.prazo.evento</code>.
	 */
	public java.lang.String getEvento() {
		return (java.lang.String) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.sql.Date, java.lang.String> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.sql.Date, java.lang.String> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.gtmelo.sistci_api.data.tables.Prazo.PRAZO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field2() {
		return com.github.gtmelo.sistci_api.data.tables.Prazo.PRAZO.DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.github.gtmelo.sistci_api.data.tables.Prazo.PRAZO.EVENTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value2() {
		return getData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getEvento();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PrazoRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PrazoRecord value2(java.sql.Date value) {
		setData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PrazoRecord value3(java.lang.String value) {
		setEvento(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PrazoRecord values(java.lang.Integer value1, java.sql.Date value2, java.lang.String value3) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PrazoRecord
	 */
	public PrazoRecord() {
		super(com.github.gtmelo.sistci_api.data.tables.Prazo.PRAZO);
	}

	/**
	 * Create a detached, initialised PrazoRecord
	 */
	public PrazoRecord(java.lang.Integer id, java.sql.Date data, java.lang.String evento) {
		super(com.github.gtmelo.sistci_api.data.tables.Prazo.PRAZO);

		setValue(0, id);
		setValue(1, data);
		setValue(2, evento);
	}
}
