/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;


import com.github.gtmelo.sistci_api.data.tables.Prorrogacao;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProrrogacaoRecord extends UpdatableRecordImpl<ProrrogacaoRecord> implements Record3<Integer, Integer, Integer> {

    private static final long serialVersionUID = 1045428587;

    /**
     * Setter for <code>sistci.prorrogacao.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sistci.prorrogacao.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistci.prorrogacao.prazoid</code>.
     */
    public void setPrazoid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sistci.prorrogacao.prazoid</code>.
     */
    public Integer getPrazoid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sistci.prorrogacao.operacaoid</code>.
     */
    public void setOperacaoid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sistci.prorrogacao.operacaoid</code>.
     */
    public Integer getOperacaoid() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<Integer, Integer, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Prorrogacao.PRORROGACAO.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Prorrogacao.PRORROGACAO.PRAZOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Prorrogacao.PRORROGACAO.OPERACAOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getPrazoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOperacaoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProrrogacaoRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProrrogacaoRecord value2(Integer value) {
        setPrazoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProrrogacaoRecord value3(Integer value) {
        setOperacaoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProrrogacaoRecord values(Integer value1, Integer value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProrrogacaoRecord
     */
    public ProrrogacaoRecord() {
        super(Prorrogacao.PRORROGACAO);
    }

    /**
     * Create a detached, initialised ProrrogacaoRecord
     */
    public ProrrogacaoRecord(Integer id, Integer prazoid, Integer operacaoid) {
        super(Prorrogacao.PRORROGACAO);

        set(0, id);
        set(1, prazoid);
        set(2, operacaoid);
    }
}
