/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReclassificacaoRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord> implements org.jooq.Record7<java.lang.Integer, java.sql.Date, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = 1733221488;

	/**
	 * Setter for <code>sistci.reclassificacao.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sistci.reclassificacao.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sistci.reclassificacao.data</code>.
	 */
	public void setData(java.sql.Date value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sistci.reclassificacao.data</code>.
	 */
	public java.sql.Date getData() {
		return (java.sql.Date) getValue(1);
	}

	/**
	 * Setter for <code>sistci.reclassificacao.imagem</code>.
	 */
	public void setImagem(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sistci.reclassificacao.imagem</code>.
	 */
	public java.lang.String getImagem() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>sistci.reclassificacao.grau_sigiloid</code>.
	 */
	public void setGrauSigiloid(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sistci.reclassificacao.grau_sigiloid</code>.
	 */
	public java.lang.Integer getGrauSigiloid() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>sistci.reclassificacao.pessoaid</code>.
	 */
	public void setPessoaid(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sistci.reclassificacao.pessoaid</code>.
	 */
	public java.lang.Integer getPessoaid() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>sistci.reclassificacao.autoridadeid</code>.
	 */
	public void setAutoridadeid(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sistci.reclassificacao.autoridadeid</code>.
	 */
	public java.lang.Integer getAutoridadeid() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>sistci.reclassificacao.tciid</code>.
	 */
	public void setTciid(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sistci.reclassificacao.tciid</code>.
	 */
	public java.lang.Integer getTciid() {
		return (java.lang.Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.sql.Date, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.sql.Date, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.gtmelo.sistci_api.data.tables.Reclassificacao.RECLASSIFICACAO.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field2() {
		return com.github.gtmelo.sistci_api.data.tables.Reclassificacao.RECLASSIFICACAO.DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.github.gtmelo.sistci_api.data.tables.Reclassificacao.RECLASSIFICACAO.IMAGEM;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.github.gtmelo.sistci_api.data.tables.Reclassificacao.RECLASSIFICACAO.GRAU_SIGILOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.github.gtmelo.sistci_api.data.tables.Reclassificacao.RECLASSIFICACAO.PESSOAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.github.gtmelo.sistci_api.data.tables.Reclassificacao.RECLASSIFICACAO.AUTORIDADEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.github.gtmelo.sistci_api.data.tables.Reclassificacao.RECLASSIFICACAO.TCIID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value2() {
		return getData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getImagem();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getGrauSigiloid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getPessoaid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getAutoridadeid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getTciid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReclassificacaoRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReclassificacaoRecord value2(java.sql.Date value) {
		setData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReclassificacaoRecord value3(java.lang.String value) {
		setImagem(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReclassificacaoRecord value4(java.lang.Integer value) {
		setGrauSigiloid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReclassificacaoRecord value5(java.lang.Integer value) {
		setPessoaid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReclassificacaoRecord value6(java.lang.Integer value) {
		setAutoridadeid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReclassificacaoRecord value7(java.lang.Integer value) {
		setTciid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ReclassificacaoRecord values(java.lang.Integer value1, java.sql.Date value2, java.lang.String value3, java.lang.Integer value4, java.lang.Integer value5, java.lang.Integer value6, java.lang.Integer value7) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ReclassificacaoRecord
	 */
	public ReclassificacaoRecord() {
		super(com.github.gtmelo.sistci_api.data.tables.Reclassificacao.RECLASSIFICACAO);
	}

	/**
	 * Create a detached, initialised ReclassificacaoRecord
	 */
	public ReclassificacaoRecord(java.lang.Integer id, java.sql.Date data, java.lang.String imagem, java.lang.Integer grauSigiloid, java.lang.Integer pessoaid, java.lang.Integer autoridadeid, java.lang.Integer tciid) {
		super(com.github.gtmelo.sistci_api.data.tables.Reclassificacao.RECLASSIFICACAO);

		setValue(0, id);
		setValue(1, data);
		setValue(2, imagem);
		setValue(3, grauSigiloid);
		setValue(4, pessoaid);
		setValue(5, autoridadeid);
		setValue(6, tciid);
	}
}
