/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;


import com.github.gtmelo.sistci_api.data.tables.Tci;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TciRecord extends UpdatableRecordImpl<TciRecord> implements Record13<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, Date, String, String> {

    private static final long serialVersionUID = -901365795;

    /**
     * Setter for <code>sistci.tci.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>sistci.tci.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>sistci.tci.orgaoid</code>.
     */
    public void setOrgaoid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>sistci.tci.orgaoid</code>.
     */
    public Integer getOrgaoid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>sistci.tci.pessoaid</code>.
     */
    public void setPessoaid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>sistci.tci.pessoaid</code>.
     */
    public Integer getPessoaid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>sistci.tci.categoriaid</code>.
     */
    public void setCategoriaid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>sistci.tci.categoriaid</code>.
     */
    public Integer getCategoriaid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>sistci.tci.prazoid</code>.
     */
    public void setPrazoid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>sistci.tci.prazoid</code>.
     */
    public Integer getPrazoid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>sistci.tci.fundamento_legalid</code>.
     */
    public void setFundamentoLegalid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>sistci.tci.fundamento_legalid</code>.
     */
    public Integer getFundamentoLegalid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>sistci.tci.grau_sigiloid</code>.
     */
    public void setGrauSigiloid(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>sistci.tci.grau_sigiloid</code>.
     */
    public Integer getGrauSigiloid() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>sistci.tci.statusid</code>.
     */
    public void setStatusid(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>sistci.tci.statusid</code>.
     */
    public Integer getStatusid() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>sistci.tci.cidicid</code>.
     */
    public void setCidicid(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>sistci.tci.cidicid</code>.
     */
    public Integer getCidicid() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>sistci.tci.nup</code>.
     */
    public void setNup(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>sistci.tci.nup</code>.
     */
    public String getNup() {
        return (String) get(9);
    }

    /**
     * Setter for <code>sistci.tci.data_producao</code>.
     */
    public void setDataProducao(Date value) {
        set(10, value);
    }

    /**
     * Getter for <code>sistci.tci.data_producao</code>.
     */
    public Date getDataProducao() {
        return (Date) get(10);
    }

    /**
     * Setter for <code>sistci.tci.tipo</code>.
     */
    public void setTipo(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>sistci.tci.tipo</code>.
     */
    public String getTipo() {
        return (String) get(11);
    }

    /**
     * Setter for <code>sistci.tci.razao_classificacao</code>.
     */
    public void setRazaoClassificacao(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>sistci.tci.razao_classificacao</code>.
     */
    public String getRazaoClassificacao() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, Date, String, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer, String, Date, String, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Tci.TCI.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Tci.TCI.ORGAOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Tci.TCI.PESSOAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Tci.TCI.CATEGORIAID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Tci.TCI.PRAZOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Tci.TCI.FUNDAMENTO_LEGALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Tci.TCI.GRAU_SIGILOID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Tci.TCI.STATUSID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return Tci.TCI.CIDICID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Tci.TCI.NUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field11() {
        return Tci.TCI.DATA_PRODUCAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Tci.TCI.TIPO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Tci.TCI.RAZAO_CLASSIFICACAO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrgaoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPessoaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCategoriaid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPrazoid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getFundamentoLegalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getGrauSigiloid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getStatusid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getCidicid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getNup();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value11() {
        return getDataProducao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getTipo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getRazaoClassificacao();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TciRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TciRecord value2(Integer value) {
        setOrgaoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TciRecord value3(Integer value) {
        setPessoaid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TciRecord value4(Integer value) {
        setCategoriaid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TciRecord value5(Integer value) {
        setPrazoid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TciRecord value6(Integer value) {
        setFundamentoLegalid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TciRecord value7(Integer value) {
        setGrauSigiloid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TciRecord value8(Integer value) {
        setStatusid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TciRecord value9(Integer value) {
        setCidicid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TciRecord value10(String value) {
        setNup(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TciRecord value11(Date value) {
        setDataProducao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TciRecord value12(String value) {
        setTipo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TciRecord value13(String value) {
        setRazaoClassificacao(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TciRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7, Integer value8, Integer value9, String value10, Date value11, String value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TciRecord
     */
    public TciRecord() {
        super(Tci.TCI);
    }

    /**
     * Create a detached, initialised TciRecord
     */
    public TciRecord(Integer id, Integer orgaoid, Integer pessoaid, Integer categoriaid, Integer prazoid, Integer fundamentoLegalid, Integer grauSigiloid, Integer statusid, Integer cidicid, String nup, Date dataProducao, String tipo, String razaoClassificacao) {
        super(Tci.TCI);

        set(0, id);
        set(1, orgaoid);
        set(2, pessoaid);
        set(3, categoriaid);
        set(4, prazoid);
        set(5, fundamentoLegalid);
        set(6, grauSigiloid);
        set(7, statusid);
        set(8, cidicid);
        set(9, nup);
        set(10, dataProducao);
        set(11, tipo);
        set(12, razaoClassificacao);
    }
}
