/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TciRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.gtmelo.sistci_api.data.tables.records.TciRecord> implements org.jooq.Record12<java.lang.Integer, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -461648525;

	/**
	 * Setter for <code>sistci.tci.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sistci.tci.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sistci.tci.data_producao</code>.
	 */
	public void setDataProducao(java.sql.Date value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sistci.tci.data_producao</code>.
	 */
	public java.sql.Date getDataProducao() {
		return (java.sql.Date) getValue(1);
	}

	/**
	 * Setter for <code>sistci.tci.tipo_documento</code>.
	 */
	public void setTipoDocumento(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sistci.tci.tipo_documento</code>.
	 */
	public java.lang.String getTipoDocumento() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>sistci.tci.razao_classificacao</code>.
	 */
	public void setRazaoClassificacao(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sistci.tci.razao_classificacao</code>.
	 */
	public java.lang.String getRazaoClassificacao() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>sistci.tci.nup</code>.
	 */
	public void setNup(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sistci.tci.nup</code>.
	 */
	public java.lang.String getNup() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>sistci.tci.cidic</code>.
	 */
	public void setCidic(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sistci.tci.cidic</code>.
	 */
	public java.lang.String getCidic() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>sistci.tci.orgaoid</code>.
	 */
	public void setOrgaoid(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sistci.tci.orgaoid</code>.
	 */
	public java.lang.Integer getOrgaoid() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>sistci.tci.categoriaid</code>.
	 */
	public void setCategoriaid(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>sistci.tci.categoriaid</code>.
	 */
	public java.lang.Integer getCategoriaid() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>sistci.tci.prazoid</code>.
	 */
	public void setPrazoid(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>sistci.tci.prazoid</code>.
	 */
	public java.lang.Integer getPrazoid() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>sistci.tci.fundamento_legalid</code>.
	 */
	public void setFundamentoLegalid(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>sistci.tci.fundamento_legalid</code>.
	 */
	public java.lang.Integer getFundamentoLegalid() {
		return (java.lang.Integer) getValue(9);
	}

	/**
	 * Setter for <code>sistci.tci.grau_sigiloid</code>.
	 */
	public void setGrauSigiloid(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>sistci.tci.grau_sigiloid</code>.
	 */
	public java.lang.Integer getGrauSigiloid() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>sistci.tci.statusid</code>.
	 */
	public void setStatusid(java.lang.Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>sistci.tci.statusid</code>.
	 */
	public java.lang.Integer getStatusid() {
		return (java.lang.Integer) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Integer, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Integer, java.sql.Date, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field2() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.DATA_PRODUCAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.TIPO_DOCUMENTO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.RAZAO_CLASSIFICACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.NUP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.CIDIC;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.ORGAOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.CATEGORIAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.PRAZOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.FUNDAMENTO_LEGALID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.GRAU_SIGILOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field12() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.STATUSID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value2() {
		return getDataProducao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getTipoDocumento();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getRazaoClassificacao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getNup();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getCidic();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getOrgaoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getCategoriaid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getPrazoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getFundamentoLegalid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getGrauSigiloid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value12() {
		return getStatusid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value2(java.sql.Date value) {
		setDataProducao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value3(java.lang.String value) {
		setTipoDocumento(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value4(java.lang.String value) {
		setRazaoClassificacao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value5(java.lang.String value) {
		setNup(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value6(java.lang.String value) {
		setCidic(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value7(java.lang.Integer value) {
		setOrgaoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value8(java.lang.Integer value) {
		setCategoriaid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value9(java.lang.Integer value) {
		setPrazoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value10(java.lang.Integer value) {
		setFundamentoLegalid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value11(java.lang.Integer value) {
		setGrauSigiloid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value12(java.lang.Integer value) {
		setStatusid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord values(java.lang.Integer value1, java.sql.Date value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.Integer value7, java.lang.Integer value8, java.lang.Integer value9, java.lang.Integer value10, java.lang.Integer value11, java.lang.Integer value12) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TciRecord
	 */
	public TciRecord() {
		super(com.github.gtmelo.sistci_api.data.tables.Tci.TCI);
	}

	/**
	 * Create a detached, initialised TciRecord
	 */
	public TciRecord(java.lang.Integer id, java.sql.Date dataProducao, java.lang.String tipoDocumento, java.lang.String razaoClassificacao, java.lang.String nup, java.lang.String cidic, java.lang.Integer orgaoid, java.lang.Integer categoriaid, java.lang.Integer prazoid, java.lang.Integer fundamentoLegalid, java.lang.Integer grauSigiloid, java.lang.Integer statusid) {
		super(com.github.gtmelo.sistci_api.data.tables.Tci.TCI);

		setValue(0, id);
		setValue(1, dataProducao);
		setValue(2, tipoDocumento);
		setValue(3, razaoClassificacao);
		setValue(4, nup);
		setValue(5, cidic);
		setValue(6, orgaoid);
		setValue(7, categoriaid);
		setValue(8, prazoid);
		setValue(9, fundamentoLegalid);
		setValue(10, grauSigiloid);
		setValue(11, statusid);
	}
}
