/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TciRecord extends org.jooq.impl.UpdatableRecordImpl<com.github.gtmelo.sistci_api.data.tables.records.TciRecord> implements org.jooq.Record13<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Date, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = -1962412128;

	/**
	 * Setter for <code>sistci.tci.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sistci.tci.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sistci.tci.orgaoid</code>.
	 */
	public void setOrgaoid(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sistci.tci.orgaoid</code>.
	 */
	public java.lang.Integer getOrgaoid() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>sistci.tci.pessoaid</code>.
	 */
	public void setPessoaid(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sistci.tci.pessoaid</code>.
	 */
	public java.lang.Integer getPessoaid() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>sistci.tci.categoriaid</code>.
	 */
	public void setCategoriaid(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sistci.tci.categoriaid</code>.
	 */
	public java.lang.Integer getCategoriaid() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>sistci.tci.prazoid</code>.
	 */
	public void setPrazoid(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sistci.tci.prazoid</code>.
	 */
	public java.lang.Integer getPrazoid() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>sistci.tci.fundamento_legalid</code>.
	 */
	public void setFundamentoLegalid(java.lang.Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sistci.tci.fundamento_legalid</code>.
	 */
	public java.lang.Integer getFundamentoLegalid() {
		return (java.lang.Integer) getValue(5);
	}

	/**
	 * Setter for <code>sistci.tci.grau_sigiloid</code>.
	 */
	public void setGrauSigiloid(java.lang.Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sistci.tci.grau_sigiloid</code>.
	 */
	public java.lang.Integer getGrauSigiloid() {
		return (java.lang.Integer) getValue(6);
	}

	/**
	 * Setter for <code>sistci.tci.statusid</code>.
	 */
	public void setStatusid(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>sistci.tci.statusid</code>.
	 */
	public java.lang.Integer getStatusid() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>sistci.tci.cidicid</code>.
	 */
	public void setCidicid(java.lang.Integer value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>sistci.tci.cidicid</code>.
	 */
	public java.lang.Integer getCidicid() {
		return (java.lang.Integer) getValue(8);
	}

	/**
	 * Setter for <code>sistci.tci.nup</code>.
	 */
	public void setNup(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>sistci.tci.nup</code>.
	 */
	public java.lang.String getNup() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>sistci.tci.data_producao</code>.
	 */
	public void setDataProducao(java.sql.Date value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>sistci.tci.data_producao</code>.
	 */
	public java.sql.Date getDataProducao() {
		return (java.sql.Date) getValue(10);
	}

	/**
	 * Setter for <code>sistci.tci.tipo</code>.
	 */
	public void setTipo(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>sistci.tci.tipo</code>.
	 */
	public java.lang.String getTipo() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>sistci.tci.razao_classificacao</code>.
	 */
	public void setRazaoClassificacao(java.lang.String value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>sistci.tci.razao_classificacao</code>.
	 */
	public java.lang.String getRazaoClassificacao() {
		return (java.lang.String) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Date, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.sql.Date, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.ORGAOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.PESSOAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.CATEGORIAID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.PRAZOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field6() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.FUNDAMENTO_LEGALID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field7() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.GRAU_SIGILOID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.STATUSID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field9() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.CIDICID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.NUP;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Date> field11() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.DATA_PRODUCAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.TIPO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field13() {
		return com.github.gtmelo.sistci_api.data.tables.Tci.TCI.RAZAO_CLASSIFICACAO;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getOrgaoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getPessoaid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getCategoriaid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getPrazoid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value6() {
		return getFundamentoLegalid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value7() {
		return getGrauSigiloid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getStatusid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value9() {
		return getCidicid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getNup();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Date value11() {
		return getDataProducao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getTipo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value13() {
		return getRazaoClassificacao();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value2(java.lang.Integer value) {
		setOrgaoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value3(java.lang.Integer value) {
		setPessoaid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value4(java.lang.Integer value) {
		setCategoriaid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value5(java.lang.Integer value) {
		setPrazoid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value6(java.lang.Integer value) {
		setFundamentoLegalid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value7(java.lang.Integer value) {
		setGrauSigiloid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value8(java.lang.Integer value) {
		setStatusid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value9(java.lang.Integer value) {
		setCidicid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value10(java.lang.String value) {
		setNup(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value11(java.sql.Date value) {
		setDataProducao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value12(java.lang.String value) {
		setTipo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord value13(java.lang.String value) {
		setRazaoClassificacao(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TciRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.Integer value4, java.lang.Integer value5, java.lang.Integer value6, java.lang.Integer value7, java.lang.Integer value8, java.lang.Integer value9, java.lang.String value10, java.sql.Date value11, java.lang.String value12, java.lang.String value13) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TciRecord
	 */
	public TciRecord() {
		super(com.github.gtmelo.sistci_api.data.tables.Tci.TCI);
	}

	/**
	 * Create a detached, initialised TciRecord
	 */
	public TciRecord(java.lang.Integer id, java.lang.Integer orgaoid, java.lang.Integer pessoaid, java.lang.Integer categoriaid, java.lang.Integer prazoid, java.lang.Integer fundamentoLegalid, java.lang.Integer grauSigiloid, java.lang.Integer statusid, java.lang.Integer cidicid, java.lang.String nup, java.sql.Date dataProducao, java.lang.String tipo, java.lang.String razaoClassificacao) {
		super(com.github.gtmelo.sistci_api.data.tables.Tci.TCI);

		setValue(0, id);
		setValue(1, orgaoid);
		setValue(2, pessoaid);
		setValue(3, categoriaid);
		setValue(4, prazoid);
		setValue(5, fundamentoLegalid);
		setValue(6, grauSigiloid);
		setValue(7, statusid);
		setValue(8, cidicid);
		setValue(9, nup);
		setValue(10, dataProducao);
		setValue(11, tipo);
		setValue(12, razaoClassificacao);
	}
}
