/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data;


import com.github.gtmelo.sistci_api.data.tables.AutoridadeRatificadora;
import com.github.gtmelo.sistci_api.data.tables.Cargo;
import com.github.gtmelo.sistci_api.data.tables.Categoria;
import com.github.gtmelo.sistci_api.data.tables.Cidic;
import com.github.gtmelo.sistci_api.data.tables.Classificacao;
import com.github.gtmelo.sistci_api.data.tables.Cpads;
import com.github.gtmelo.sistci_api.data.tables.CpadsPessoa;
import com.github.gtmelo.sistci_api.data.tables.Desclassificacao;
import com.github.gtmelo.sistci_api.data.tables.Email;
import com.github.gtmelo.sistci_api.data.tables.FundamentoLegal;
import com.github.gtmelo.sistci_api.data.tables.GrauSigilo;
import com.github.gtmelo.sistci_api.data.tables.Operacao;
import com.github.gtmelo.sistci_api.data.tables.Organizacao;
import com.github.gtmelo.sistci_api.data.tables.Orgao;
import com.github.gtmelo.sistci_api.data.tables.Pessoa;
import com.github.gtmelo.sistci_api.data.tables.Prazo;
import com.github.gtmelo.sistci_api.data.tables.Prorrogacao;
import com.github.gtmelo.sistci_api.data.tables.Reclassificacao;
import com.github.gtmelo.sistci_api.data.tables.Reducao;
import com.github.gtmelo.sistci_api.data.tables.Status;
import com.github.gtmelo.sistci_api.data.tables.Tci;
import com.github.gtmelo.sistci_api.data.tables.records.AutoridadeRatificadoraRecord;
import com.github.gtmelo.sistci_api.data.tables.records.CargoRecord;
import com.github.gtmelo.sistci_api.data.tables.records.CategoriaRecord;
import com.github.gtmelo.sistci_api.data.tables.records.CidicRecord;
import com.github.gtmelo.sistci_api.data.tables.records.ClassificacaoRecord;
import com.github.gtmelo.sistci_api.data.tables.records.CpadsPessoaRecord;
import com.github.gtmelo.sistci_api.data.tables.records.CpadsRecord;
import com.github.gtmelo.sistci_api.data.tables.records.DesclassificacaoRecord;
import com.github.gtmelo.sistci_api.data.tables.records.EmailRecord;
import com.github.gtmelo.sistci_api.data.tables.records.FundamentoLegalRecord;
import com.github.gtmelo.sistci_api.data.tables.records.GrauSigiloRecord;
import com.github.gtmelo.sistci_api.data.tables.records.OperacaoRecord;
import com.github.gtmelo.sistci_api.data.tables.records.OrganizacaoRecord;
import com.github.gtmelo.sistci_api.data.tables.records.OrgaoRecord;
import com.github.gtmelo.sistci_api.data.tables.records.PessoaRecord;
import com.github.gtmelo.sistci_api.data.tables.records.PrazoRecord;
import com.github.gtmelo.sistci_api.data.tables.records.ProrrogacaoRecord;
import com.github.gtmelo.sistci_api.data.tables.records.ReclassificacaoRecord;
import com.github.gtmelo.sistci_api.data.tables.records.ReducaoRecord;
import com.github.gtmelo.sistci_api.data.tables.records.StatusRecord;
import com.github.gtmelo.sistci_api.data.tables.records.TciRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>sistci</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<AutoridadeRatificadoraRecord, Integer> IDENTITY_AUTORIDADE_RATIFICADORA = Identities0.IDENTITY_AUTORIDADE_RATIFICADORA;
    public static final Identity<CargoRecord, Integer> IDENTITY_CARGO = Identities0.IDENTITY_CARGO;
    public static final Identity<CategoriaRecord, Integer> IDENTITY_CATEGORIA = Identities0.IDENTITY_CATEGORIA;
    public static final Identity<CidicRecord, Integer> IDENTITY_CIDIC = Identities0.IDENTITY_CIDIC;
    public static final Identity<ClassificacaoRecord, Integer> IDENTITY_CLASSIFICACAO = Identities0.IDENTITY_CLASSIFICACAO;
    public static final Identity<CpadsRecord, Integer> IDENTITY_CPADS = Identities0.IDENTITY_CPADS;
    public static final Identity<DesclassificacaoRecord, Integer> IDENTITY_DESCLASSIFICACAO = Identities0.IDENTITY_DESCLASSIFICACAO;
    public static final Identity<EmailRecord, Integer> IDENTITY_EMAIL = Identities0.IDENTITY_EMAIL;
    public static final Identity<FundamentoLegalRecord, Integer> IDENTITY_FUNDAMENTO_LEGAL = Identities0.IDENTITY_FUNDAMENTO_LEGAL;
    public static final Identity<GrauSigiloRecord, Integer> IDENTITY_GRAU_SIGILO = Identities0.IDENTITY_GRAU_SIGILO;
    public static final Identity<OperacaoRecord, Integer> IDENTITY_OPERACAO = Identities0.IDENTITY_OPERACAO;
    public static final Identity<OrganizacaoRecord, Integer> IDENTITY_ORGANIZACAO = Identities0.IDENTITY_ORGANIZACAO;
    public static final Identity<OrgaoRecord, Integer> IDENTITY_ORGAO = Identities0.IDENTITY_ORGAO;
    public static final Identity<PessoaRecord, Integer> IDENTITY_PESSOA = Identities0.IDENTITY_PESSOA;
    public static final Identity<PrazoRecord, Integer> IDENTITY_PRAZO = Identities0.IDENTITY_PRAZO;
    public static final Identity<ProrrogacaoRecord, Integer> IDENTITY_PRORROGACAO = Identities0.IDENTITY_PRORROGACAO;
    public static final Identity<ReclassificacaoRecord, Integer> IDENTITY_RECLASSIFICACAO = Identities0.IDENTITY_RECLASSIFICACAO;
    public static final Identity<ReducaoRecord, Integer> IDENTITY_REDUCAO = Identities0.IDENTITY_REDUCAO;
    public static final Identity<StatusRecord, Integer> IDENTITY_STATUS = Identities0.IDENTITY_STATUS;
    public static final Identity<TciRecord, Integer> IDENTITY_TCI = Identities0.IDENTITY_TCI;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AutoridadeRatificadoraRecord> KEY_AUTORIDADE_RATIFICADORA_PRIMARY = UniqueKeys0.KEY_AUTORIDADE_RATIFICADORA_PRIMARY;
    public static final UniqueKey<CargoRecord> KEY_CARGO_PRIMARY = UniqueKeys0.KEY_CARGO_PRIMARY;
    public static final UniqueKey<CategoriaRecord> KEY_CATEGORIA_PRIMARY = UniqueKeys0.KEY_CATEGORIA_PRIMARY;
    public static final UniqueKey<CidicRecord> KEY_CIDIC_PRIMARY = UniqueKeys0.KEY_CIDIC_PRIMARY;
    public static final UniqueKey<ClassificacaoRecord> KEY_CLASSIFICACAO_PRIMARY = UniqueKeys0.KEY_CLASSIFICACAO_PRIMARY;
    public static final UniqueKey<CpadsRecord> KEY_CPADS_PRIMARY = UniqueKeys0.KEY_CPADS_PRIMARY;
    public static final UniqueKey<CpadsPessoaRecord> KEY_CPADS_PESSOA_PRIMARY = UniqueKeys0.KEY_CPADS_PESSOA_PRIMARY;
    public static final UniqueKey<DesclassificacaoRecord> KEY_DESCLASSIFICACAO_PRIMARY = UniqueKeys0.KEY_DESCLASSIFICACAO_PRIMARY;
    public static final UniqueKey<EmailRecord> KEY_EMAIL_PRIMARY = UniqueKeys0.KEY_EMAIL_PRIMARY;
    public static final UniqueKey<EmailRecord> KEY_EMAIL_EMAIL = UniqueKeys0.KEY_EMAIL_EMAIL;
    public static final UniqueKey<FundamentoLegalRecord> KEY_FUNDAMENTO_LEGAL_PRIMARY = UniqueKeys0.KEY_FUNDAMENTO_LEGAL_PRIMARY;
    public static final UniqueKey<GrauSigiloRecord> KEY_GRAU_SIGILO_PRIMARY = UniqueKeys0.KEY_GRAU_SIGILO_PRIMARY;
    public static final UniqueKey<GrauSigiloRecord> KEY_GRAU_SIGILO_ABREVIACAO = UniqueKeys0.KEY_GRAU_SIGILO_ABREVIACAO;
    public static final UniqueKey<OperacaoRecord> KEY_OPERACAO_PRIMARY = UniqueKeys0.KEY_OPERACAO_PRIMARY;
    public static final UniqueKey<OrganizacaoRecord> KEY_ORGANIZACAO_PRIMARY = UniqueKeys0.KEY_ORGANIZACAO_PRIMARY;
    public static final UniqueKey<OrgaoRecord> KEY_ORGAO_PRIMARY = UniqueKeys0.KEY_ORGAO_PRIMARY;
    public static final UniqueKey<PessoaRecord> KEY_PESSOA_PRIMARY = UniqueKeys0.KEY_PESSOA_PRIMARY;
    public static final UniqueKey<PrazoRecord> KEY_PRAZO_PRIMARY = UniqueKeys0.KEY_PRAZO_PRIMARY;
    public static final UniqueKey<ProrrogacaoRecord> KEY_PRORROGACAO_PRIMARY = UniqueKeys0.KEY_PRORROGACAO_PRIMARY;
    public static final UniqueKey<ReclassificacaoRecord> KEY_RECLASSIFICACAO_PRIMARY = UniqueKeys0.KEY_RECLASSIFICACAO_PRIMARY;
    public static final UniqueKey<ReducaoRecord> KEY_REDUCAO_PRIMARY = UniqueKeys0.KEY_REDUCAO_PRIMARY;
    public static final UniqueKey<StatusRecord> KEY_STATUS_PRIMARY = UniqueKeys0.KEY_STATUS_PRIMARY;
    public static final UniqueKey<TciRecord> KEY_TCI_PRIMARY = UniqueKeys0.KEY_TCI_PRIMARY;
    public static final UniqueKey<TciRecord> KEY_TCI_NUP = UniqueKeys0.KEY_TCI_NUP;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CargoRecord, OrgaoRecord> CARGO_ORGAO = ForeignKeys0.CARGO_ORGAO;
    public static final ForeignKey<ClassificacaoRecord, AutoridadeRatificadoraRecord> CLASSIFICACAO_AUTORIDADE_RATIFICADORA = ForeignKeys0.CLASSIFICACAO_AUTORIDADE_RATIFICADORA;
    public static final ForeignKey<ClassificacaoRecord, OperacaoRecord> FKCLASSIFICA26679 = ForeignKeys0.FKCLASSIFICA26679;
    public static final ForeignKey<CpadsRecord, OrgaoRecord> ORGAO_CPADS = ForeignKeys0.ORGAO_CPADS;
    public static final ForeignKey<CpadsPessoaRecord, CpadsRecord> CPADS_PESSOA = ForeignKeys0.CPADS_PESSOA;
    public static final ForeignKey<CpadsPessoaRecord, PessoaRecord> FKCPADS_PESS956983 = ForeignKeys0.FKCPADS_PESS956983;
    public static final ForeignKey<DesclassificacaoRecord, OperacaoRecord> FKDESCLASSIF626384 = ForeignKeys0.FKDESCLASSIF626384;
    public static final ForeignKey<OperacaoRecord, StatusRecord> OPERACAO_STATUS = ForeignKeys0.OPERACAO_STATUS;
    public static final ForeignKey<OperacaoRecord, PessoaRecord> PESSOA_OPERACAO = ForeignKeys0.PESSOA_OPERACAO;
    public static final ForeignKey<OperacaoRecord, PessoaRecord> AUTORIDADE_OPERACAO = ForeignKeys0.AUTORIDADE_OPERACAO;
    public static final ForeignKey<OperacaoRecord, TciRecord> TCI_OPERACAO = ForeignKeys0.TCI_OPERACAO;
    public static final ForeignKey<OrgaoRecord, OrganizacaoRecord> ORGANIZACAO_ORGAO = ForeignKeys0.ORGANIZACAO_ORGAO;
    public static final ForeignKey<OrgaoRecord, EmailRecord> ORGAO_EMAIL = ForeignKeys0.ORGAO_EMAIL;
    public static final ForeignKey<PessoaRecord, EmailRecord> PESSOA_EMAIL = ForeignKeys0.PESSOA_EMAIL;
    public static final ForeignKey<PessoaRecord, OrgaoRecord> ORGAO_PESSOA = ForeignKeys0.ORGAO_PESSOA;
    public static final ForeignKey<PessoaRecord, CargoRecord> PESSOA_CARGO = ForeignKeys0.PESSOA_CARGO;
    public static final ForeignKey<ProrrogacaoRecord, PrazoRecord> PRORROGACAO_PRAZO = ForeignKeys0.PRORROGACAO_PRAZO;
    public static final ForeignKey<ProrrogacaoRecord, OperacaoRecord> FKPRORROGACA31355 = ForeignKeys0.FKPRORROGACA31355;
    public static final ForeignKey<ReclassificacaoRecord, GrauSigiloRecord> FKRECLASSIFI428042 = ForeignKeys0.FKRECLASSIFI428042;
    public static final ForeignKey<ReclassificacaoRecord, OperacaoRecord> FKRECLASSIFI625325 = ForeignKeys0.FKRECLASSIFI625325;
    public static final ForeignKey<ReducaoRecord, PrazoRecord> REDUCAO_PRAZO = ForeignKeys0.REDUCAO_PRAZO;
    public static final ForeignKey<ReducaoRecord, OperacaoRecord> FKREDUCAO363962 = ForeignKeys0.FKREDUCAO363962;
    public static final ForeignKey<TciRecord, OrgaoRecord> ORGAO_TCI = ForeignKeys0.ORGAO_TCI;
    public static final ForeignKey<TciRecord, PessoaRecord> PESSOA_TCI = ForeignKeys0.PESSOA_TCI;
    public static final ForeignKey<TciRecord, CategoriaRecord> TCI_CATEGORIA = ForeignKeys0.TCI_CATEGORIA;
    public static final ForeignKey<TciRecord, PrazoRecord> TCI_PRAZO = ForeignKeys0.TCI_PRAZO;
    public static final ForeignKey<TciRecord, FundamentoLegalRecord> TCI_FUNDAMENTO_LEGAL = ForeignKeys0.TCI_FUNDAMENTO_LEGAL;
    public static final ForeignKey<TciRecord, GrauSigiloRecord> TCI_GRAU_SIGILO = ForeignKeys0.TCI_GRAU_SIGILO;
    public static final ForeignKey<TciRecord, StatusRecord> TCI_STATUS = ForeignKeys0.TCI_STATUS;
    public static final ForeignKey<TciRecord, CidicRecord> TCI_CIDIC = ForeignKeys0.TCI_CIDIC;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<AutoridadeRatificadoraRecord, Integer> IDENTITY_AUTORIDADE_RATIFICADORA = createIdentity(AutoridadeRatificadora.AUTORIDADE_RATIFICADORA, AutoridadeRatificadora.AUTORIDADE_RATIFICADORA.ID);
        public static Identity<CargoRecord, Integer> IDENTITY_CARGO = createIdentity(Cargo.CARGO, Cargo.CARGO.ID);
        public static Identity<CategoriaRecord, Integer> IDENTITY_CATEGORIA = createIdentity(Categoria.CATEGORIA, Categoria.CATEGORIA.ID);
        public static Identity<CidicRecord, Integer> IDENTITY_CIDIC = createIdentity(Cidic.CIDIC, Cidic.CIDIC.ID);
        public static Identity<ClassificacaoRecord, Integer> IDENTITY_CLASSIFICACAO = createIdentity(Classificacao.CLASSIFICACAO, Classificacao.CLASSIFICACAO.ID);
        public static Identity<CpadsRecord, Integer> IDENTITY_CPADS = createIdentity(Cpads.CPADS, Cpads.CPADS.ID);
        public static Identity<DesclassificacaoRecord, Integer> IDENTITY_DESCLASSIFICACAO = createIdentity(Desclassificacao.DESCLASSIFICACAO, Desclassificacao.DESCLASSIFICACAO.ID);
        public static Identity<EmailRecord, Integer> IDENTITY_EMAIL = createIdentity(Email.EMAIL, Email.EMAIL.ID);
        public static Identity<FundamentoLegalRecord, Integer> IDENTITY_FUNDAMENTO_LEGAL = createIdentity(FundamentoLegal.FUNDAMENTO_LEGAL, FundamentoLegal.FUNDAMENTO_LEGAL.ID);
        public static Identity<GrauSigiloRecord, Integer> IDENTITY_GRAU_SIGILO = createIdentity(GrauSigilo.GRAU_SIGILO, GrauSigilo.GRAU_SIGILO.ID);
        public static Identity<OperacaoRecord, Integer> IDENTITY_OPERACAO = createIdentity(Operacao.OPERACAO, Operacao.OPERACAO.ID);
        public static Identity<OrganizacaoRecord, Integer> IDENTITY_ORGANIZACAO = createIdentity(Organizacao.ORGANIZACAO, Organizacao.ORGANIZACAO.ID);
        public static Identity<OrgaoRecord, Integer> IDENTITY_ORGAO = createIdentity(Orgao.ORGAO, Orgao.ORGAO.ID);
        public static Identity<PessoaRecord, Integer> IDENTITY_PESSOA = createIdentity(Pessoa.PESSOA, Pessoa.PESSOA.ID);
        public static Identity<PrazoRecord, Integer> IDENTITY_PRAZO = createIdentity(Prazo.PRAZO, Prazo.PRAZO.ID);
        public static Identity<ProrrogacaoRecord, Integer> IDENTITY_PRORROGACAO = createIdentity(Prorrogacao.PRORROGACAO, Prorrogacao.PRORROGACAO.ID);
        public static Identity<ReclassificacaoRecord, Integer> IDENTITY_RECLASSIFICACAO = createIdentity(Reclassificacao.RECLASSIFICACAO, Reclassificacao.RECLASSIFICACAO.ID);
        public static Identity<ReducaoRecord, Integer> IDENTITY_REDUCAO = createIdentity(Reducao.REDUCAO, Reducao.REDUCAO.ID);
        public static Identity<StatusRecord, Integer> IDENTITY_STATUS = createIdentity(Status.STATUS, Status.STATUS.ID);
        public static Identity<TciRecord, Integer> IDENTITY_TCI = createIdentity(Tci.TCI, Tci.TCI.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<AutoridadeRatificadoraRecord> KEY_AUTORIDADE_RATIFICADORA_PRIMARY = createUniqueKey(AutoridadeRatificadora.AUTORIDADE_RATIFICADORA, "KEY_autoridade_ratificadora_PRIMARY", AutoridadeRatificadora.AUTORIDADE_RATIFICADORA.ID);
        public static final UniqueKey<CargoRecord> KEY_CARGO_PRIMARY = createUniqueKey(Cargo.CARGO, "KEY_cargo_PRIMARY", Cargo.CARGO.ID);
        public static final UniqueKey<CategoriaRecord> KEY_CATEGORIA_PRIMARY = createUniqueKey(Categoria.CATEGORIA, "KEY_categoria_PRIMARY", Categoria.CATEGORIA.ID);
        public static final UniqueKey<CidicRecord> KEY_CIDIC_PRIMARY = createUniqueKey(Cidic.CIDIC, "KEY_cidic_PRIMARY", Cidic.CIDIC.ID);
        public static final UniqueKey<ClassificacaoRecord> KEY_CLASSIFICACAO_PRIMARY = createUniqueKey(Classificacao.CLASSIFICACAO, "KEY_classificacao_PRIMARY", Classificacao.CLASSIFICACAO.ID);
        public static final UniqueKey<CpadsRecord> KEY_CPADS_PRIMARY = createUniqueKey(Cpads.CPADS, "KEY_cpads_PRIMARY", Cpads.CPADS.ID);
        public static final UniqueKey<CpadsPessoaRecord> KEY_CPADS_PESSOA_PRIMARY = createUniqueKey(CpadsPessoa.CPADS_PESSOA, "KEY_cpads_pessoa_PRIMARY", CpadsPessoa.CPADS_PESSOA.CPADSID, CpadsPessoa.CPADS_PESSOA.PESSOAID);
        public static final UniqueKey<DesclassificacaoRecord> KEY_DESCLASSIFICACAO_PRIMARY = createUniqueKey(Desclassificacao.DESCLASSIFICACAO, "KEY_desclassificacao_PRIMARY", Desclassificacao.DESCLASSIFICACAO.ID);
        public static final UniqueKey<EmailRecord> KEY_EMAIL_PRIMARY = createUniqueKey(Email.EMAIL, "KEY_email_PRIMARY", Email.EMAIL.ID);
        public static final UniqueKey<EmailRecord> KEY_EMAIL_EMAIL = createUniqueKey(Email.EMAIL, "KEY_email_email", Email.EMAIL.EMAIL_);
        public static final UniqueKey<FundamentoLegalRecord> KEY_FUNDAMENTO_LEGAL_PRIMARY = createUniqueKey(FundamentoLegal.FUNDAMENTO_LEGAL, "KEY_fundamento_legal_PRIMARY", FundamentoLegal.FUNDAMENTO_LEGAL.ID);
        public static final UniqueKey<GrauSigiloRecord> KEY_GRAU_SIGILO_PRIMARY = createUniqueKey(GrauSigilo.GRAU_SIGILO, "KEY_grau_sigilo_PRIMARY", GrauSigilo.GRAU_SIGILO.ID);
        public static final UniqueKey<GrauSigiloRecord> KEY_GRAU_SIGILO_ABREVIACAO = createUniqueKey(GrauSigilo.GRAU_SIGILO, "KEY_grau_sigilo_abreviacao", GrauSigilo.GRAU_SIGILO.ABREVIACAO);
        public static final UniqueKey<OperacaoRecord> KEY_OPERACAO_PRIMARY = createUniqueKey(Operacao.OPERACAO, "KEY_operacao_PRIMARY", Operacao.OPERACAO.ID);
        public static final UniqueKey<OrganizacaoRecord> KEY_ORGANIZACAO_PRIMARY = createUniqueKey(Organizacao.ORGANIZACAO, "KEY_organizacao_PRIMARY", Organizacao.ORGANIZACAO.ID);
        public static final UniqueKey<OrgaoRecord> KEY_ORGAO_PRIMARY = createUniqueKey(Orgao.ORGAO, "KEY_orgao_PRIMARY", Orgao.ORGAO.ID);
        public static final UniqueKey<PessoaRecord> KEY_PESSOA_PRIMARY = createUniqueKey(Pessoa.PESSOA, "KEY_pessoa_PRIMARY", Pessoa.PESSOA.ID);
        public static final UniqueKey<PrazoRecord> KEY_PRAZO_PRIMARY = createUniqueKey(Prazo.PRAZO, "KEY_prazo_PRIMARY", Prazo.PRAZO.ID);
        public static final UniqueKey<ProrrogacaoRecord> KEY_PRORROGACAO_PRIMARY = createUniqueKey(Prorrogacao.PRORROGACAO, "KEY_prorrogacao_PRIMARY", Prorrogacao.PRORROGACAO.ID);
        public static final UniqueKey<ReclassificacaoRecord> KEY_RECLASSIFICACAO_PRIMARY = createUniqueKey(Reclassificacao.RECLASSIFICACAO, "KEY_reclassificacao_PRIMARY", Reclassificacao.RECLASSIFICACAO.ID);
        public static final UniqueKey<ReducaoRecord> KEY_REDUCAO_PRIMARY = createUniqueKey(Reducao.REDUCAO, "KEY_reducao_PRIMARY", Reducao.REDUCAO.ID);
        public static final UniqueKey<StatusRecord> KEY_STATUS_PRIMARY = createUniqueKey(Status.STATUS, "KEY_status_PRIMARY", Status.STATUS.ID);
        public static final UniqueKey<TciRecord> KEY_TCI_PRIMARY = createUniqueKey(Tci.TCI, "KEY_tci_PRIMARY", Tci.TCI.ID);
        public static final UniqueKey<TciRecord> KEY_TCI_NUP = createUniqueKey(Tci.TCI, "KEY_tci_nup", Tci.TCI.NUP);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<CargoRecord, OrgaoRecord> CARGO_ORGAO = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_ORGAO_PRIMARY, Cargo.CARGO, "cargo_orgao", Cargo.CARGO.ORGAOID);
        public static final ForeignKey<ClassificacaoRecord, AutoridadeRatificadoraRecord> CLASSIFICACAO_AUTORIDADE_RATIFICADORA = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_AUTORIDADE_RATIFICADORA_PRIMARY, Classificacao.CLASSIFICACAO, "classificacao_autoridade_ratificadora", Classificacao.CLASSIFICACAO.AUTORIDADE_RATIFICADORAID);
        public static final ForeignKey<ClassificacaoRecord, OperacaoRecord> FKCLASSIFICA26679 = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_OPERACAO_PRIMARY, Classificacao.CLASSIFICACAO, "FKclassifica26679", Classificacao.CLASSIFICACAO.OPERACAOID);
        public static final ForeignKey<CpadsRecord, OrgaoRecord> ORGAO_CPADS = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_ORGAO_PRIMARY, Cpads.CPADS, "orgao_cpads", Cpads.CPADS.ORGAOID);
        public static final ForeignKey<CpadsPessoaRecord, CpadsRecord> CPADS_PESSOA = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_CPADS_PRIMARY, CpadsPessoa.CPADS_PESSOA, "cpads_pessoa", CpadsPessoa.CPADS_PESSOA.CPADSID);
        public static final ForeignKey<CpadsPessoaRecord, PessoaRecord> FKCPADS_PESS956983 = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_PESSOA_PRIMARY, CpadsPessoa.CPADS_PESSOA, "FKcpads_pess956983", CpadsPessoa.CPADS_PESSOA.PESSOAID);
        public static final ForeignKey<DesclassificacaoRecord, OperacaoRecord> FKDESCLASSIF626384 = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_OPERACAO_PRIMARY, Desclassificacao.DESCLASSIFICACAO, "FKdesclassif626384", Desclassificacao.DESCLASSIFICACAO.OPERACAOID);
        public static final ForeignKey<OperacaoRecord, StatusRecord> OPERACAO_STATUS = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_STATUS_PRIMARY, Operacao.OPERACAO, "operacao_status", Operacao.OPERACAO.STATUSID);
        public static final ForeignKey<OperacaoRecord, PessoaRecord> PESSOA_OPERACAO = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_PESSOA_PRIMARY, Operacao.OPERACAO, "pessoa_operacao", Operacao.OPERACAO.PESSOAID);
        public static final ForeignKey<OperacaoRecord, PessoaRecord> AUTORIDADE_OPERACAO = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_PESSOA_PRIMARY, Operacao.OPERACAO, "autoridade_operacao", Operacao.OPERACAO.AUTORIDADEID);
        public static final ForeignKey<OperacaoRecord, TciRecord> TCI_OPERACAO = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_TCI_PRIMARY, Operacao.OPERACAO, "tci_operacao", Operacao.OPERACAO.TCIID);
        public static final ForeignKey<OrgaoRecord, OrganizacaoRecord> ORGANIZACAO_ORGAO = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_ORGANIZACAO_PRIMARY, Orgao.ORGAO, "organizacao_orgao", Orgao.ORGAO.ORGANIZACAOID);
        public static final ForeignKey<OrgaoRecord, EmailRecord> ORGAO_EMAIL = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_EMAIL_PRIMARY, Orgao.ORGAO, "orgao_email", Orgao.ORGAO.EMAILID);
        public static final ForeignKey<PessoaRecord, EmailRecord> PESSOA_EMAIL = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_EMAIL_PRIMARY, Pessoa.PESSOA, "pessoa_email", Pessoa.PESSOA.EMAILID);
        public static final ForeignKey<PessoaRecord, OrgaoRecord> ORGAO_PESSOA = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_ORGAO_PRIMARY, Pessoa.PESSOA, "orgao_pessoa", Pessoa.PESSOA.ORGAOID);
        public static final ForeignKey<PessoaRecord, CargoRecord> PESSOA_CARGO = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_CARGO_PRIMARY, Pessoa.PESSOA, "pessoa_cargo", Pessoa.PESSOA.CARGOID);
        public static final ForeignKey<ProrrogacaoRecord, PrazoRecord> PRORROGACAO_PRAZO = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_PRAZO_PRIMARY, Prorrogacao.PRORROGACAO, "prorrogacao_prazo", Prorrogacao.PRORROGACAO.PRAZOID);
        public static final ForeignKey<ProrrogacaoRecord, OperacaoRecord> FKPRORROGACA31355 = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_OPERACAO_PRIMARY, Prorrogacao.PRORROGACAO, "FKprorrogaca31355", Prorrogacao.PRORROGACAO.OPERACAOID);
        public static final ForeignKey<ReclassificacaoRecord, GrauSigiloRecord> FKRECLASSIFI428042 = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_GRAU_SIGILO_PRIMARY, Reclassificacao.RECLASSIFICACAO, "FKreclassifi428042", Reclassificacao.RECLASSIFICACAO.GRAU_SIGILOID);
        public static final ForeignKey<ReclassificacaoRecord, OperacaoRecord> FKRECLASSIFI625325 = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_OPERACAO_PRIMARY, Reclassificacao.RECLASSIFICACAO, "FKreclassifi625325", Reclassificacao.RECLASSIFICACAO.OPERACAOID);
        public static final ForeignKey<ReducaoRecord, PrazoRecord> REDUCAO_PRAZO = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_PRAZO_PRIMARY, Reducao.REDUCAO, "reducao_prazo", Reducao.REDUCAO.PRAZOID);
        public static final ForeignKey<ReducaoRecord, OperacaoRecord> FKREDUCAO363962 = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_OPERACAO_PRIMARY, Reducao.REDUCAO, "FKreducao363962", Reducao.REDUCAO.OPERACAOID);
        public static final ForeignKey<TciRecord, OrgaoRecord> ORGAO_TCI = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_ORGAO_PRIMARY, Tci.TCI, "orgao_tci", Tci.TCI.ORGAOID);
        public static final ForeignKey<TciRecord, PessoaRecord> PESSOA_TCI = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_PESSOA_PRIMARY, Tci.TCI, "pessoa_tci", Tci.TCI.PESSOAID);
        public static final ForeignKey<TciRecord, CategoriaRecord> TCI_CATEGORIA = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_CATEGORIA_PRIMARY, Tci.TCI, "tci_categoria", Tci.TCI.CATEGORIAID);
        public static final ForeignKey<TciRecord, PrazoRecord> TCI_PRAZO = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_PRAZO_PRIMARY, Tci.TCI, "tci_prazo", Tci.TCI.PRAZOID);
        public static final ForeignKey<TciRecord, FundamentoLegalRecord> TCI_FUNDAMENTO_LEGAL = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_FUNDAMENTO_LEGAL_PRIMARY, Tci.TCI, "tci_fundamento_legal", Tci.TCI.FUNDAMENTO_LEGALID);
        public static final ForeignKey<TciRecord, GrauSigiloRecord> TCI_GRAU_SIGILO = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_GRAU_SIGILO_PRIMARY, Tci.TCI, "tci_grau_sigilo", Tci.TCI.GRAU_SIGILOID);
        public static final ForeignKey<TciRecord, StatusRecord> TCI_STATUS = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_STATUS_PRIMARY, Tci.TCI, "tci_status", Tci.TCI.STATUSID);
        public static final ForeignKey<TciRecord, CidicRecord> TCI_CIDIC = createForeignKey(com.github.gtmelo.sistci_api.data.Keys.KEY_CIDIC_PRIMARY, Tci.TCI, "tci_cidic", Tci.TCI.CIDICID);
    }
}
