/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data;


import com.github.gtmelo.sistci_api.data.tables.AutoridadeRatificadora;
import com.github.gtmelo.sistci_api.data.tables.Cargo;
import com.github.gtmelo.sistci_api.data.tables.Categoria;
import com.github.gtmelo.sistci_api.data.tables.Cidic;
import com.github.gtmelo.sistci_api.data.tables.Classificacao;
import com.github.gtmelo.sistci_api.data.tables.Cpads;
import com.github.gtmelo.sistci_api.data.tables.CpadsPessoa;
import com.github.gtmelo.sistci_api.data.tables.Desclassificacao;
import com.github.gtmelo.sistci_api.data.tables.Email;
import com.github.gtmelo.sistci_api.data.tables.FundamentoLegal;
import com.github.gtmelo.sistci_api.data.tables.GrauSigilo;
import com.github.gtmelo.sistci_api.data.tables.Operacao;
import com.github.gtmelo.sistci_api.data.tables.Organizacao;
import com.github.gtmelo.sistci_api.data.tables.Orgao;
import com.github.gtmelo.sistci_api.data.tables.Pessoa;
import com.github.gtmelo.sistci_api.data.tables.Prazo;
import com.github.gtmelo.sistci_api.data.tables.Prorrogacao;
import com.github.gtmelo.sistci_api.data.tables.Reclassificacao;
import com.github.gtmelo.sistci_api.data.tables.Reducao;
import com.github.gtmelo.sistci_api.data.tables.Status;
import com.github.gtmelo.sistci_api.data.tables.Tci;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in sistci
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sistci.autoridade_ratificadora</code>.
     */
    public static final AutoridadeRatificadora AUTORIDADE_RATIFICADORA = com.github.gtmelo.sistci_api.data.tables.AutoridadeRatificadora.AUTORIDADE_RATIFICADORA;

    /**
     * The table <code>sistci.cargo</code>.
     */
    public static final Cargo CARGO = com.github.gtmelo.sistci_api.data.tables.Cargo.CARGO;

    /**
     * The table <code>sistci.categoria</code>.
     */
    public static final Categoria CATEGORIA = com.github.gtmelo.sistci_api.data.tables.Categoria.CATEGORIA;

    /**
     * The table <code>sistci.cidic</code>.
     */
    public static final Cidic CIDIC = com.github.gtmelo.sistci_api.data.tables.Cidic.CIDIC;

    /**
     * The table <code>sistci.classificacao</code>.
     */
    public static final Classificacao CLASSIFICACAO = com.github.gtmelo.sistci_api.data.tables.Classificacao.CLASSIFICACAO;

    /**
     * The table <code>sistci.cpads</code>.
     */
    public static final Cpads CPADS = com.github.gtmelo.sistci_api.data.tables.Cpads.CPADS;

    /**
     * The table <code>sistci.cpads_pessoa</code>.
     */
    public static final CpadsPessoa CPADS_PESSOA = com.github.gtmelo.sistci_api.data.tables.CpadsPessoa.CPADS_PESSOA;

    /**
     * The table <code>sistci.desclassificacao</code>.
     */
    public static final Desclassificacao DESCLASSIFICACAO = com.github.gtmelo.sistci_api.data.tables.Desclassificacao.DESCLASSIFICACAO;

    /**
     * The table <code>sistci.email</code>.
     */
    public static final Email EMAIL = com.github.gtmelo.sistci_api.data.tables.Email.EMAIL;

    /**
     * The table <code>sistci.fundamento_legal</code>.
     */
    public static final FundamentoLegal FUNDAMENTO_LEGAL = com.github.gtmelo.sistci_api.data.tables.FundamentoLegal.FUNDAMENTO_LEGAL;

    /**
     * The table <code>sistci.grau_sigilo</code>.
     */
    public static final GrauSigilo GRAU_SIGILO = com.github.gtmelo.sistci_api.data.tables.GrauSigilo.GRAU_SIGILO;

    /**
     * The table <code>sistci.operacao</code>.
     */
    public static final Operacao OPERACAO = com.github.gtmelo.sistci_api.data.tables.Operacao.OPERACAO;

    /**
     * The table <code>sistci.organizacao</code>.
     */
    public static final Organizacao ORGANIZACAO = com.github.gtmelo.sistci_api.data.tables.Organizacao.ORGANIZACAO;

    /**
     * The table <code>sistci.orgao</code>.
     */
    public static final Orgao ORGAO = com.github.gtmelo.sistci_api.data.tables.Orgao.ORGAO;

    /**
     * The table <code>sistci.pessoa</code>.
     */
    public static final Pessoa PESSOA = com.github.gtmelo.sistci_api.data.tables.Pessoa.PESSOA;

    /**
     * The table <code>sistci.prazo</code>.
     */
    public static final Prazo PRAZO = com.github.gtmelo.sistci_api.data.tables.Prazo.PRAZO;

    /**
     * The table <code>sistci.prorrogacao</code>.
     */
    public static final Prorrogacao PRORROGACAO = com.github.gtmelo.sistci_api.data.tables.Prorrogacao.PRORROGACAO;

    /**
     * The table <code>sistci.reclassificacao</code>.
     */
    public static final Reclassificacao RECLASSIFICACAO = com.github.gtmelo.sistci_api.data.tables.Reclassificacao.RECLASSIFICACAO;

    /**
     * The table <code>sistci.reducao</code>.
     */
    public static final Reducao REDUCAO = com.github.gtmelo.sistci_api.data.tables.Reducao.REDUCAO;

    /**
     * The table <code>sistci.status</code>.
     */
    public static final Status STATUS = com.github.gtmelo.sistci_api.data.tables.Status.STATUS;

    /**
     * The table <code>sistci.tci</code>.
     */
    public static final Tci TCI = com.github.gtmelo.sistci_api.data.tables.Tci.TCI;
}
