/**
 * This class is generated by jOOQ
 */
package com.github.gtmelo.sistci_api.data;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in sistci
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.4.5" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table sistci.alteracao_prazo
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.AlteracaoPrazo ALTERACAO_PRAZO = com.github.gtmelo.sistci_api.data.tables.AlteracaoPrazo.ALTERACAO_PRAZO;

	/**
	 * The table sistci.alteracao_prazo_tci
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.AlteracaoPrazoTci ALTERACAO_PRAZO_TCI = com.github.gtmelo.sistci_api.data.tables.AlteracaoPrazoTci.ALTERACAO_PRAZO_TCI;

	/**
	 * The table sistci.cargo
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Cargo CARGO = com.github.gtmelo.sistci_api.data.tables.Cargo.CARGO;

	/**
	 * The table sistci.categoria
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Categoria CATEGORIA = com.github.gtmelo.sistci_api.data.tables.Categoria.CATEGORIA;

	/**
	 * The table sistci.classificacao
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Classificacao CLASSIFICACAO = com.github.gtmelo.sistci_api.data.tables.Classificacao.CLASSIFICACAO;

	/**
	 * The table sistci.cpads
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Cpads CPADS = com.github.gtmelo.sistci_api.data.tables.Cpads.CPADS;

	/**
	 * The table sistci.cpads_pessoa
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.CpadsPessoa CPADS_PESSOA = com.github.gtmelo.sistci_api.data.tables.CpadsPessoa.CPADS_PESSOA;

	/**
	 * The table sistci.desclassificacao
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Desclassificacao DESCLASSIFICACAO = com.github.gtmelo.sistci_api.data.tables.Desclassificacao.DESCLASSIFICACAO;

	/**
	 * The table sistci.email
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Email EMAIL = com.github.gtmelo.sistci_api.data.tables.Email.EMAIL;

	/**
	 * The table sistci.fundamento_legal
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.FundamentoLegal FUNDAMENTO_LEGAL = com.github.gtmelo.sistci_api.data.tables.FundamentoLegal.FUNDAMENTO_LEGAL;

	/**
	 * The table sistci.grau_sigilo
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.GrauSigilo GRAU_SIGILO = com.github.gtmelo.sistci_api.data.tables.GrauSigilo.GRAU_SIGILO;

	/**
	 * The table sistci.minuta
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Minuta MINUTA = com.github.gtmelo.sistci_api.data.tables.Minuta.MINUTA;

	/**
	 * The table sistci.orgao
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Orgao ORGAO = com.github.gtmelo.sistci_api.data.tables.Orgao.ORGAO;

	/**
	 * The table sistci.pessoa
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Pessoa PESSOA = com.github.gtmelo.sistci_api.data.tables.Pessoa.PESSOA;

	/**
	 * The table sistci.prazo
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Prazo PRAZO = com.github.gtmelo.sistci_api.data.tables.Prazo.PRAZO;

	/**
	 * The table sistci.reclassificacao
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Reclassificacao RECLASSIFICACAO = com.github.gtmelo.sistci_api.data.tables.Reclassificacao.RECLASSIFICACAO;

	/**
	 * The table sistci.status
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Status STATUS = com.github.gtmelo.sistci_api.data.tables.Status.STATUS;

	/**
	 * The table sistci.tci
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.Tci TCI = com.github.gtmelo.sistci_api.data.tables.Tci.TCI;

	/**
	 * VIEW
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.ViewClassificacao VIEW_CLASSIFICACAO = com.github.gtmelo.sistci_api.data.tables.ViewClassificacao.VIEW_CLASSIFICACAO;

	/**
	 * VIEW
	 */
	public static final com.github.gtmelo.sistci_api.data.tables.ViewTci VIEW_TCI = com.github.gtmelo.sistci_api.data.tables.ViewTci.VIEW_TCI;
}
